// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'media.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_albums_by_parent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// 获取根相册列表
Future<List<AlbumWithInfo>> getRootAlbums() =>
    RustLib.instance.api.crateApiAlbumGetRootAlbums();

/// 获取子相册
Future<List<AlbumWithInfo>> getChildAlbums({required String parentId}) =>
    RustLib.instance.api.crateApiAlbumGetChildAlbums(parentId: parentId);

/// 创建相册
Future<String> createAlbum({required String name, String? parentId}) =>
    RustLib.instance.api
        .crateApiAlbumCreateAlbum(name: name, parentId: parentId);

/// 删除相册（级联删除子相册和媒体关联）
Future<void> deleteAlbum({required String id}) =>
    RustLib.instance.api.crateApiAlbumDeleteAlbum(id: id);

/// 重命名相册
Future<void> renameAlbum({required String id, required String newName}) =>
    RustLib.instance.api.crateApiAlbumRenameAlbum(id: id, newName: newName);

/// 获取相册面包屑路径
Future<List<BreadcrumbItem>> getAlbumBreadcrumb({required String albumId}) =>
    RustLib.instance.api.crateApiAlbumGetAlbumBreadcrumb(albumId: albumId);

/// 添加媒体到相册
Future<void> addMediaToAlbum(
        {required List<String> mediaIds, required String albumId}) =>
    RustLib.instance.api
        .crateApiAlbumAddMediaToAlbum(mediaIds: mediaIds, albumId: albumId);

/// 从相册移除媒体
Future<void> removeMediaFromAlbum(
        {required List<String> mediaIds, required String albumId}) =>
    RustLib.instance.api.crateApiAlbumRemoveMediaFromAlbum(
        mediaIds: mediaIds, albumId: albumId);

/// 设置相册封面
Future<void> setAlbumCover(
        {required String albumId, required String mediaId}) =>
    RustLib.instance.api
        .crateApiAlbumSetAlbumCover(albumId: albumId, mediaId: mediaId);

/// 获取相册内的媒体列表
Future<List<MediaItem>> getMediaByAlbum({required String albumId}) =>
    RustLib.instance.api.crateApiAlbumGetMediaByAlbum(albumId: albumId);

/// 确保默认相册存在（如果不存在则创建）
Future<String> ensureDefaultAlbum({required String name}) =>
    RustLib.instance.api.crateApiAlbumEnsureDefaultAlbum(name: name);

/// 相册实体
class Album {
  final String id;
  final String name;
  final String? parentId;
  final String? coverMediaId;
  final int sortOrder;
  final PlatformInt64 createdAt;

  const Album({
    required this.id,
    required this.name,
    this.parentId,
    this.coverMediaId,
    required this.sortOrder,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      coverMediaId.hashCode ^
      sortOrder.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Album &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          coverMediaId == other.coverMediaId &&
          sortOrder == other.sortOrder &&
          createdAt == other.createdAt;
}

/// 相册信息（包含媒体数量和子相册标志）
class AlbumWithInfo {
  final Album album;
  final int mediaCount;
  final String? coverThumbnailPath;
  final int hasChildren;

  const AlbumWithInfo({
    required this.album,
    required this.mediaCount,
    this.coverThumbnailPath,
    required this.hasChildren,
  });

  @override
  int get hashCode =>
      album.hashCode ^
      mediaCount.hashCode ^
      coverThumbnailPath.hashCode ^
      hasChildren.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumWithInfo &&
          runtimeType == other.runtimeType &&
          album == other.album &&
          mediaCount == other.mediaCount &&
          coverThumbnailPath == other.coverThumbnailPath &&
          hasChildren == other.hasChildren;
}

/// 面包屑项
class BreadcrumbItem {
  final String id;
  final String name;

  const BreadcrumbItem({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreadcrumbItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
