// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 获取指定媒体的笔记（一对一，LIMIT 1）
Future<Note?> getNoteByMediaId({required String mediaId}) =>
    RustLib.instance.api.crateApiNoteGetNoteByMediaId(mediaId: mediaId);

/// 获取单条笔记
Future<Note?> getNoteById({required String id}) =>
    RustLib.instance.api.crateApiNoteGetNoteById(id: id);

/// 获取全部笔记（按 updated_at DESC）
Future<List<Note>> getAllNotes() =>
    RustLib.instance.api.crateApiNoteGetAllNotes();

/// 创建或更新笔记（Skill-14 一对一 upsert）
///
/// - 若该 media_id 已有笔记则更新 content（保留 id、created_at）
/// - 若不存在则新建
/// - 返回笔记 id
Future<String> saveNote({required String mediaId, required String content}) =>
    RustLib.instance.api
        .crateApiNoteSaveNote(mediaId: mediaId, content: content);

/// 删除笔记
Future<void> deleteNote({required String id}) =>
    RustLib.instance.api.crateApiNoteDeleteNote(id: id);

/// 笔记实体（Skill-14）
///
/// - 字段：id, media_id, content, created_at, updated_at
/// - 与媒体一对一：media_id 唯一索引 + ForeignKey.CASCADE
/// - 渲染层按 Markdown 解析（`flutter_markdown`）
class Note {
  final String id;
  final String mediaId;
  final String content;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const Note({
    required this.id,
    required this.mediaId,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mediaId.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mediaId == other.mediaId &&
          content == other.content &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
