// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `estimate_thumbnail_size`, `get_db_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// 获取设置
Future<AppSettings> getSettings() =>
    RustLib.instance.api.crateApiSettingsGetSettings();

/// 保存设置
Future<void> saveSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(settings: settings);

/// 获取存储统计
Future<StorageStats> getStorageStats() =>
    RustLib.instance.api.crateApiSettingsGetStorageStats();

/// 清理缩略图缓存（删除未被引用的缩略图文件）
Future<int> clearThumbnailCache() =>
    RustLib.instance.api.crateApiSettingsClearThumbnailCache();

/// 导出数据（导出数据库备份）
Future<void> exportData({required String exportPath}) =>
    RustLib.instance.api.crateApiSettingsExportData(exportPath: exportPath);

/// 导入数据（从 SQLite 备份文件恢复）
///
/// 注意：此函数会替换数据库文件。调用后需要重启应用以重新初始化数据库连接池。
Future<void> importData({required String importPath}) =>
    RustLib.instance.api.crateApiSettingsImportData(importPath: importPath);

/// 删除所有数据
Future<void> deleteAllData() =>
    RustLib.instance.api.crateApiSettingsDeleteAllData();

/// 查找未引用的媒体文件（磁盘上存在但数据库中没有记录的文件）
Future<List<String>> findUnreferencedFiles() =>
    RustLib.instance.api.crateApiSettingsFindUnreferencedFiles();

/// 删除未引用的媒体文件
Future<int> deleteUnreferencedFiles() =>
    RustLib.instance.api.crateApiSettingsDeleteUnreferencedFiles();

/// 初始化应用（初始化数据库连接池）
///
/// 在 Android 上，app_dir 应该传入应用的私有目录（如 getApplicationDocumentsDirectory）
/// 在桌面上，可以传入当前工作目录或用户数据目录
Future<void> initApp({required String appDir}) =>
    RustLib.instance.api.crateApiSettingsInitApp(appDir: appDir);

/// 应用设置
class AppSettings {
  /// 主题模式 (system/light/dark) - 默认: system
  final ThemeMode themeMode;

  /// 网格列数 - 默认: 3
  final int gridColumns;

  /// 相册网格列数 - 默认: 2
  final int albumGridColumns;

  /// 缩略图质量 1-100 - 默认: 85
  final int thumbnailQuality;

  /// 语言 (system/zh/en) - 默认: system
  final String language;

  /// 动态颜色 (Android 12+) - 默认: true
  final int dynamicColor;

  /// 上次扫描路径 - 默认: 空
  final String lastScanPath;

  const AppSettings({
    required this.themeMode,
    required this.gridColumns,
    required this.albumGridColumns,
    required this.thumbnailQuality,
    required this.language,
    required this.dynamicColor,
    required this.lastScanPath,
  });

  @override
  int get hashCode =>
      themeMode.hashCode ^
      gridColumns.hashCode ^
      albumGridColumns.hashCode ^
      thumbnailQuality.hashCode ^
      language.hashCode ^
      dynamicColor.hashCode ^
      lastScanPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          gridColumns == other.gridColumns &&
          albumGridColumns == other.albumGridColumns &&
          thumbnailQuality == other.thumbnailQuality &&
          language == other.language &&
          dynamicColor == other.dynamicColor &&
          lastScanPath == other.lastScanPath;
}

/// 存储统计
class StorageStats {
  final int totalMediaCount;
  final PlatformInt64 totalSize;
  final PlatformInt64 thumbnailCacheSize;
  final PlatformInt64 databaseSize;

  const StorageStats({
    required this.totalMediaCount,
    required this.totalSize,
    required this.thumbnailCacheSize,
    required this.databaseSize,
  });

  @override
  int get hashCode =>
      totalMediaCount.hashCode ^
      totalSize.hashCode ^
      thumbnailCacheSize.hashCode ^
      databaseSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageStats &&
          runtimeType == other.runtimeType &&
          totalMediaCount == other.totalMediaCount &&
          totalSize == other.totalSize &&
          thumbnailCacheSize == other.thumbnailCacheSize &&
          databaseSize == other.databaseSize;
}

/// 主题模式
enum ThemeMode {
  system,
  light,
  dark,
  ;
}
