// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/album.dart';
import 'api/import_export.dart';
import 'api/media.dart';
import 'api/note.dart';
import 'api/scanner.dart';
import 'api/search.dart';
import 'api/settings.dart';
import 'api/tag.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdjacentMedia dco_decode_adjacent_media(dynamic raw);

  @protected
  Album dco_decode_album(dynamic raw);

  @protected
  AlbumWithInfo dco_decode_album_with_info(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AdjacentMedia dco_decode_box_autoadd_adjacent_media(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MediaItem dco_decode_box_autoadd_media_item(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  SearchFilter dco_decode_box_autoadd_search_filter(dynamic raw);

  @protected
  BreadcrumbItem dco_decode_breadcrumb_item(dynamic raw);

  @protected
  ConflictStrategy dco_decode_conflict_strategy(dynamic raw);

  @protected
  ExportProgress dco_decode_export_progress(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportProgress dco_decode_import_progress(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlbumWithInfo> dco_decode_list_album_with_info(dynamic raw);

  @protected
  List<BreadcrumbItem> dco_decode_list_breadcrumb_item(dynamic raw);

  @protected
  List<MediaItem> dco_decode_list_media_item(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw);

  @protected
  List<TagBreadcrumb> dco_decode_list_tag_breadcrumb(dynamic raw);

  @protected
  List<TagWithInfo> dco_decode_list_tag_with_info(dynamic raw);

  @protected
  MediaItem dco_decode_media_item(dynamic raw);

  @protected
  MediaType dco_decode_media_type(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AdjacentMedia? dco_decode_opt_box_autoadd_adjacent_media(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MediaItem? dco_decode_opt_box_autoadd_media_item(dynamic raw);

  @protected
  Note? dco_decode_opt_box_autoadd_note(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  ScanResult dco_decode_scan_result(dynamic raw);

  @protected
  SearchFilter dco_decode_search_filter(dynamic raw);

  @protected
  StorageStats dco_decode_storage_stats(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  TagBreadcrumb dco_decode_tag_breadcrumb(dynamic raw);

  @protected
  TagWithInfo dco_decode_tag_with_info(dynamic raw);

  @protected
  ThemeMode dco_decode_theme_mode(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdjacentMedia sse_decode_adjacent_media(SseDeserializer deserializer);

  @protected
  Album sse_decode_album(SseDeserializer deserializer);

  @protected
  AlbumWithInfo sse_decode_album_with_info(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AdjacentMedia sse_decode_box_autoadd_adjacent_media(
      SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaItem sse_decode_box_autoadd_media_item(SseDeserializer deserializer);

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_box_autoadd_search_filter(
      SseDeserializer deserializer);

  @protected
  BreadcrumbItem sse_decode_breadcrumb_item(SseDeserializer deserializer);

  @protected
  ConflictStrategy sse_decode_conflict_strategy(SseDeserializer deserializer);

  @protected
  ExportProgress sse_decode_export_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportProgress sse_decode_import_progress(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlbumWithInfo> sse_decode_list_album_with_info(
      SseDeserializer deserializer);

  @protected
  List<BreadcrumbItem> sse_decode_list_breadcrumb_item(
      SseDeserializer deserializer);

  @protected
  List<MediaItem> sse_decode_list_media_item(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer);

  @protected
  List<TagBreadcrumb> sse_decode_list_tag_breadcrumb(
      SseDeserializer deserializer);

  @protected
  List<TagWithInfo> sse_decode_list_tag_with_info(SseDeserializer deserializer);

  @protected
  MediaItem sse_decode_media_item(SseDeserializer deserializer);

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer);

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AdjacentMedia? sse_decode_opt_box_autoadd_adjacent_media(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaItem? sse_decode_opt_box_autoadd_media_item(
      SseDeserializer deserializer);

  @protected
  Note? sse_decode_opt_box_autoadd_note(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  ScanResult sse_decode_scan_result(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_search_filter(SseDeserializer deserializer);

  @protected
  StorageStats sse_decode_storage_stats(SseDeserializer deserializer);

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  TagBreadcrumb sse_decode_tag_breadcrumb(SseDeserializer deserializer);

  @protected
  TagWithInfo sse_decode_tag_with_info(SseDeserializer deserializer);

  @protected
  ThemeMode sse_decode_theme_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_adjacent_media> cst_encode_box_autoadd_adjacent_media(
      AdjacentMedia raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_adjacent_media();
    cst_api_fill_to_wire_adjacent_media(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_app_settings> cst_encode_box_autoadd_app_settings(
      AppSettings raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_app_settings();
    cst_api_fill_to_wire_app_settings(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_32(cst_encode_i_32(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_media_item> cst_encode_box_autoadd_media_item(
      MediaItem raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_media_item();
    cst_api_fill_to_wire_media_item(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_note> cst_encode_box_autoadd_note(Note raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_note();
    cst_api_fill_to_wire_note(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_search_filter> cst_encode_box_autoadd_search_filter(
      SearchFilter raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_search_filter();
    cst_api_fill_to_wire_search_filter(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_album_with_info> cst_encode_list_album_with_info(
      List<AlbumWithInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_album_with_info(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_album_with_info(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_breadcrumb_item> cst_encode_list_breadcrumb_item(
      List<BreadcrumbItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_breadcrumb_item(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_breadcrumb_item(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_media_item> cst_encode_list_media_item(
      List<MediaItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_media_item(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_media_item(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_tag> cst_encode_list_tag(List<Tag> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_tag(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_tag(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_tag_breadcrumb> cst_encode_list_tag_breadcrumb(
      List<TagBreadcrumb> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_tag_breadcrumb(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_tag_breadcrumb(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_tag_with_info> cst_encode_list_tag_with_info(
      List<TagWithInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_tag_with_info(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_tag_with_info(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_adjacent_media>
      cst_encode_opt_box_autoadd_adjacent_media(AdjacentMedia? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_adjacent_media(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_media_item> cst_encode_opt_box_autoadd_media_item(
      MediaItem? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_media_item(raw);
  }

  @protected
  ffi.Pointer<wire_cst_note> cst_encode_opt_box_autoadd_note(Note? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_note(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_opt_list_String(
      List<String>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_String(raw);
  }

  @protected
  void cst_api_fill_to_wire_adjacent_media(
      AdjacentMedia apiObj, wire_cst_adjacent_media wireObj) {
    wireObj.previous = cst_encode_opt_box_autoadd_media_item(apiObj.previous);
    cst_api_fill_to_wire_media_item(apiObj.current, wireObj.current);
    wireObj.next = cst_encode_opt_box_autoadd_media_item(apiObj.next);
  }

  @protected
  void cst_api_fill_to_wire_album(Album apiObj, wire_cst_album wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.parent_id = cst_encode_opt_String(apiObj.parentId);
    wireObj.cover_media_id = cst_encode_opt_String(apiObj.coverMediaId);
    wireObj.sort_order = cst_encode_i_32(apiObj.sortOrder);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_album_with_info(
      AlbumWithInfo apiObj, wire_cst_album_with_info wireObj) {
    cst_api_fill_to_wire_album(apiObj.album, wireObj.album);
    wireObj.media_count = cst_encode_i_32(apiObj.mediaCount);
    wireObj.cover_thumbnail_path =
        cst_encode_opt_String(apiObj.coverThumbnailPath);
    wireObj.has_children = cst_encode_bool(apiObj.hasChildren);
  }

  @protected
  void cst_api_fill_to_wire_app_settings(
      AppSettings apiObj, wire_cst_app_settings wireObj) {
    wireObj.theme_mode = cst_encode_theme_mode(apiObj.themeMode);
    wireObj.grid_columns = cst_encode_i_32(apiObj.gridColumns);
    wireObj.album_grid_columns = cst_encode_i_32(apiObj.albumGridColumns);
    wireObj.show_content_previews = cst_encode_bool(apiObj.showContentPreviews);
    wireObj.thumbnail_quality = cst_encode_i_32(apiObj.thumbnailQuality);
    wireObj.language = cst_encode_String(apiObj.language);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_adjacent_media(
      AdjacentMedia apiObj, ffi.Pointer<wire_cst_adjacent_media> wireObj) {
    cst_api_fill_to_wire_adjacent_media(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_app_settings(
      AppSettings apiObj, ffi.Pointer<wire_cst_app_settings> wireObj) {
    cst_api_fill_to_wire_app_settings(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_media_item(
      MediaItem apiObj, ffi.Pointer<wire_cst_media_item> wireObj) {
    cst_api_fill_to_wire_media_item(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_note(
      Note apiObj, ffi.Pointer<wire_cst_note> wireObj) {
    cst_api_fill_to_wire_note(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_search_filter(
      SearchFilter apiObj, ffi.Pointer<wire_cst_search_filter> wireObj) {
    cst_api_fill_to_wire_search_filter(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_breadcrumb_item(
      BreadcrumbItem apiObj, wire_cst_breadcrumb_item wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
  }

  @protected
  void cst_api_fill_to_wire_export_progress(
      ExportProgress apiObj, wire_cst_export_progress wireObj) {
    wireObj.total_files = cst_encode_i_32(apiObj.totalFiles);
    wireObj.processed_files = cst_encode_i_32(apiObj.processedFiles);
    wireObj.current_file = cst_encode_opt_String(apiObj.currentFile);
    wireObj.status = cst_encode_String(apiObj.status);
  }

  @protected
  void cst_api_fill_to_wire_import_progress(
      ImportProgress apiObj, wire_cst_import_progress wireObj) {
    wireObj.total_files = cst_encode_i_32(apiObj.totalFiles);
    wireObj.processed_files = cst_encode_i_32(apiObj.processedFiles);
    wireObj.current_phase = cst_encode_String(apiObj.currentPhase);
    wireObj.status = cst_encode_String(apiObj.status);
  }

  @protected
  void cst_api_fill_to_wire_media_item(
      MediaItem apiObj, wire_cst_media_item wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.original_name = cst_encode_String(apiObj.originalName);
    wireObj.storage_name = cst_encode_String(apiObj.storageName);
    wireObj.file_path = cst_encode_String(apiObj.filePath);
    wireObj.thumbnail_path = cst_encode_String(apiObj.thumbnailPath);
    wireObj.media_type = cst_encode_media_type(apiObj.mediaType);
    wireObj.mime_type = cst_encode_String(apiObj.mimeType);
    wireObj.size = cst_encode_i_64(apiObj.size);
    wireObj.width = cst_encode_opt_box_autoadd_i_32(apiObj.width);
    wireObj.height = cst_encode_opt_box_autoadd_i_32(apiObj.height);
    wireObj.duration = cst_encode_opt_box_autoadd_i_64(apiObj.duration);
    wireObj.sha256_hash = cst_encode_String(apiObj.sha256Hash);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
    wireObj.updated_at = cst_encode_i_64(apiObj.updatedAt);
  }

  @protected
  void cst_api_fill_to_wire_note(Note apiObj, wire_cst_note wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.media_id = cst_encode_String(apiObj.mediaId);
    wireObj.content = cst_encode_String(apiObj.content);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
    wireObj.updated_at = cst_encode_i_64(apiObj.updatedAt);
  }

  @protected
  void cst_api_fill_to_wire_scan_result(
      ScanResult apiObj, wire_cst_scan_result wireObj) {
    wireObj.imported_count = cst_encode_i_32(apiObj.importedCount);
    wireObj.duplicate_count = cst_encode_i_32(apiObj.duplicateCount);
    wireObj.failed_count = cst_encode_i_32(apiObj.failedCount);
    wireObj.media_items = cst_encode_list_media_item(apiObj.mediaItems);
  }

  @protected
  void cst_api_fill_to_wire_search_filter(
      SearchFilter apiObj, wire_cst_search_filter wireObj) {
    wireObj.query = cst_encode_opt_String(apiObj.query);
    wireObj.media_type = cst_encode_opt_String(apiObj.mediaType);
    wireObj.start_date = cst_encode_opt_box_autoadd_i_64(apiObj.startDate);
    wireObj.end_date = cst_encode_opt_box_autoadd_i_64(apiObj.endDate);
    wireObj.album_id = cst_encode_opt_String(apiObj.albumId);
    wireObj.tag_ids = cst_encode_opt_list_String(apiObj.tagIds);
    wireObj.tag_count = cst_encode_opt_box_autoadd_i_32(apiObj.tagCount);
  }

  @protected
  void cst_api_fill_to_wire_storage_stats(
      StorageStats apiObj, wire_cst_storage_stats wireObj) {
    wireObj.total_media_count = cst_encode_i_32(apiObj.totalMediaCount);
    wireObj.total_size = cst_encode_i_64(apiObj.totalSize);
    wireObj.thumbnail_cache_size = cst_encode_i_64(apiObj.thumbnailCacheSize);
    wireObj.database_size = cst_encode_i_64(apiObj.databaseSize);
  }

  @protected
  void cst_api_fill_to_wire_tag(Tag apiObj, wire_cst_tag wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.color = cst_encode_opt_String(apiObj.color);
    wireObj.parent_id = cst_encode_opt_String(apiObj.parentId);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_tag_breadcrumb(
      TagBreadcrumb apiObj, wire_cst_tag_breadcrumb wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
  }

  @protected
  void cst_api_fill_to_wire_tag_with_info(
      TagWithInfo apiObj, wire_cst_tag_with_info wireObj) {
    cst_api_fill_to_wire_tag(apiObj.tag, wireObj.tag);
    wireObj.media_count = cst_encode_i_32(apiObj.mediaCount);
    wireObj.cover_thumbnail_path =
        cst_encode_opt_String(apiObj.coverThumbnailPath);
    wireObj.has_children = cst_encode_bool(apiObj.hasChildren);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_conflict_strategy(ConflictStrategy raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_media_type(MediaType raw);

  @protected
  int cst_encode_theme_mode(ThemeMode raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_adjacent_media(AdjacentMedia self, SseSerializer serializer);

  @protected
  void sse_encode_album(Album self, SseSerializer serializer);

  @protected
  void sse_encode_album_with_info(AlbumWithInfo self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_adjacent_media(
      AdjacentMedia self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
      AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_item(
      MediaItem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_filter(
      SearchFilter self, SseSerializer serializer);

  @protected
  void sse_encode_breadcrumb_item(
      BreadcrumbItem self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_strategy(
      ConflictStrategy self, SseSerializer serializer);

  @protected
  void sse_encode_export_progress(
      ExportProgress self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_progress(
      ImportProgress self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_with_info(
      List<AlbumWithInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_breadcrumb_item(
      List<BreadcrumbItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_item(
      List<MediaItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_breadcrumb(
      List<TagBreadcrumb> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_with_info(
      List<TagWithInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_media_item(MediaItem self, SseSerializer serializer);

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer);

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_adjacent_media(
      AdjacentMedia? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_item(
      MediaItem? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_note(Note? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_scan_result(ScanResult self, SseSerializer serializer);

  @protected
  void sse_encode_search_filter(SearchFilter self, SseSerializer serializer);

  @protected
  void sse_encode_storage_stats(StorageStats self, SseSerializer serializer);

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_tag_breadcrumb(TagBreadcrumb self, SseSerializer serializer);

  @protected
  void sse_encode_tag_with_info(TagWithInfo self, SseSerializer serializer);

  @protected
  void sse_encode_theme_mode(ThemeMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    int ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject =
      _store_dart_post_cobjectPtr.asFunction<void Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}
