// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/album.dart';
import 'api/enums.dart';
import 'api/import_export.dart';
import 'api/media.dart';
import 'api/note.dart';
import 'api/scanner.dart';
import 'api/search.dart';
import 'api/settings.dart';
import 'api/tag.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdjacentMedia dco_decode_adjacent_media(dynamic raw);

  @protected
  Album dco_decode_album(dynamic raw);

  @protected
  AlbumWithInfo dco_decode_album_with_info(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AdjacentMedia dco_decode_box_autoadd_adjacent_media(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MediaItem dco_decode_box_autoadd_media_item(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  SearchFilter dco_decode_box_autoadd_search_filter(dynamic raw);

  @protected
  BreadcrumbItem dco_decode_breadcrumb_item(dynamic raw);

  @protected
  ConflictStrategy dco_decode_conflict_strategy(dynamic raw);

  @protected
  ExportProgress dco_decode_export_progress(dynamic raw);

  @protected
  FilterMode dco_decode_filter_mode(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportProgress dco_decode_import_progress(dynamic raw);

  @protected
  LanguageSetting dco_decode_language_setting(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlbumWithInfo> dco_decode_list_album_with_info(dynamic raw);

  @protected
  List<BreadcrumbItem> dco_decode_list_breadcrumb_item(dynamic raw);

  @protected
  List<MediaItem> dco_decode_list_media_item(dynamic raw);

  @protected
  List<Note> dco_decode_list_note(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw);

  @protected
  List<TagBreadcrumb> dco_decode_list_tag_breadcrumb(dynamic raw);

  @protected
  List<TagWithInfo> dco_decode_list_tag_with_info(dynamic raw);

  @protected
  MediaItem dco_decode_media_item(dynamic raw);

  @protected
  MediaType dco_decode_media_type(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AdjacentMedia? dco_decode_opt_box_autoadd_adjacent_media(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MediaItem? dco_decode_opt_box_autoadd_media_item(dynamic raw);

  @protected
  Note? dco_decode_opt_box_autoadd_note(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  ScanResult dco_decode_scan_result(dynamic raw);

  @protected
  SearchFilter dco_decode_search_filter(dynamic raw);

  @protected
  StorageStats dco_decode_storage_stats(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  TagBreadcrumb dco_decode_tag_breadcrumb(dynamic raw);

  @protected
  TagWithInfo dco_decode_tag_with_info(dynamic raw);

  @protected
  ThemeMode dco_decode_theme_mode(dynamic raw);

  @protected
  ThemeModeSetting dco_decode_theme_mode_setting(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdjacentMedia sse_decode_adjacent_media(SseDeserializer deserializer);

  @protected
  Album sse_decode_album(SseDeserializer deserializer);

  @protected
  AlbumWithInfo sse_decode_album_with_info(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AdjacentMedia sse_decode_box_autoadd_adjacent_media(
      SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaItem sse_decode_box_autoadd_media_item(SseDeserializer deserializer);

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_box_autoadd_search_filter(
      SseDeserializer deserializer);

  @protected
  BreadcrumbItem sse_decode_breadcrumb_item(SseDeserializer deserializer);

  @protected
  ConflictStrategy sse_decode_conflict_strategy(SseDeserializer deserializer);

  @protected
  ExportProgress sse_decode_export_progress(SseDeserializer deserializer);

  @protected
  FilterMode sse_decode_filter_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportProgress sse_decode_import_progress(SseDeserializer deserializer);

  @protected
  LanguageSetting sse_decode_language_setting(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlbumWithInfo> sse_decode_list_album_with_info(
      SseDeserializer deserializer);

  @protected
  List<BreadcrumbItem> sse_decode_list_breadcrumb_item(
      SseDeserializer deserializer);

  @protected
  List<MediaItem> sse_decode_list_media_item(SseDeserializer deserializer);

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer);

  @protected
  List<TagBreadcrumb> sse_decode_list_tag_breadcrumb(
      SseDeserializer deserializer);

  @protected
  List<TagWithInfo> sse_decode_list_tag_with_info(SseDeserializer deserializer);

  @protected
  MediaItem sse_decode_media_item(SseDeserializer deserializer);

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer);

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AdjacentMedia? sse_decode_opt_box_autoadd_adjacent_media(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaItem? sse_decode_opt_box_autoadd_media_item(
      SseDeserializer deserializer);

  @protected
  Note? sse_decode_opt_box_autoadd_note(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  ScanResult sse_decode_scan_result(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_search_filter(SseDeserializer deserializer);

  @protected
  StorageStats sse_decode_storage_stats(SseDeserializer deserializer);

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  TagBreadcrumb sse_decode_tag_breadcrumb(SseDeserializer deserializer);

  @protected
  TagWithInfo sse_decode_tag_with_info(SseDeserializer deserializer);

  @protected
  ThemeMode sse_decode_theme_mode(SseDeserializer deserializer);

  @protected
  ThemeModeSetting sse_decode_theme_mode_setting(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_adjacent_media> cst_encode_box_autoadd_adjacent_media(
      AdjacentMedia raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_adjacent_media();
    cst_api_fill_to_wire_adjacent_media(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_app_settings> cst_encode_box_autoadd_app_settings(
      AppSettings raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_app_settings();
    cst_api_fill_to_wire_app_settings(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_32(cst_encode_i_32(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_media_item> cst_encode_box_autoadd_media_item(
      MediaItem raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_media_item();
    cst_api_fill_to_wire_media_item(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_note> cst_encode_box_autoadd_note(Note raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_note();
    cst_api_fill_to_wire_note(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_search_filter> cst_encode_box_autoadd_search_filter(
      SearchFilter raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_search_filter();
    cst_api_fill_to_wire_search_filter(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_album_with_info> cst_encode_list_album_with_info(
      List<AlbumWithInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_album_with_info(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_album_with_info(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_breadcrumb_item> cst_encode_list_breadcrumb_item(
      List<BreadcrumbItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_breadcrumb_item(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_breadcrumb_item(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_media_item> cst_encode_list_media_item(
      List<MediaItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_media_item(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_media_item(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_note> cst_encode_list_note(List<Note> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_note(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_note(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_tag> cst_encode_list_tag(List<Tag> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_tag(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_tag(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_tag_breadcrumb> cst_encode_list_tag_breadcrumb(
      List<TagBreadcrumb> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_tag_breadcrumb(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_tag_breadcrumb(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_tag_with_info> cst_encode_list_tag_with_info(
      List<TagWithInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_tag_with_info(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_tag_with_info(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_adjacent_media>
      cst_encode_opt_box_autoadd_adjacent_media(AdjacentMedia? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_adjacent_media(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_media_item> cst_encode_opt_box_autoadd_media_item(
      MediaItem? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_media_item(raw);
  }

  @protected
  ffi.Pointer<wire_cst_note> cst_encode_opt_box_autoadd_note(Note? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_note(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_opt_list_String(
      List<String>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_String(raw);
  }

  @protected
  void cst_api_fill_to_wire_adjacent_media(
      AdjacentMedia apiObj, wire_cst_adjacent_media wireObj) {
    wireObj.previous = cst_encode_opt_box_autoadd_media_item(apiObj.previous);
    cst_api_fill_to_wire_media_item(apiObj.current, wireObj.current);
    wireObj.next = cst_encode_opt_box_autoadd_media_item(apiObj.next);
  }

  @protected
  void cst_api_fill_to_wire_album(Album apiObj, wire_cst_album wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.parent_id = cst_encode_opt_String(apiObj.parentId);
    wireObj.cover_media_id = cst_encode_opt_String(apiObj.coverMediaId);
    wireObj.sort_order = cst_encode_i_32(apiObj.sortOrder);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_album_with_info(
      AlbumWithInfo apiObj, wire_cst_album_with_info wireObj) {
    cst_api_fill_to_wire_album(apiObj.album, wireObj.album);
    wireObj.media_count = cst_encode_i_32(apiObj.mediaCount);
    wireObj.cover_thumbnail_path =
        cst_encode_opt_String(apiObj.coverThumbnailPath);
    wireObj.has_children = cst_encode_i_32(apiObj.hasChildren);
  }

  @protected
  void cst_api_fill_to_wire_app_settings(
      AppSettings apiObj, wire_cst_app_settings wireObj) {
    wireObj.theme_mode = cst_encode_theme_mode(apiObj.themeMode);
    wireObj.grid_columns = cst_encode_i_32(apiObj.gridColumns);
    wireObj.album_grid_columns = cst_encode_i_32(apiObj.albumGridColumns);
    wireObj.show_content_previews = cst_encode_i_32(apiObj.showContentPreviews);
    wireObj.thumbnail_quality = cst_encode_i_32(apiObj.thumbnailQuality);
    wireObj.language = cst_encode_String(apiObj.language);
    wireObj.dynamic_color = cst_encode_i_32(apiObj.dynamicColor);
    wireObj.last_scan_path = cst_encode_String(apiObj.lastScanPath);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_adjacent_media(
      AdjacentMedia apiObj, ffi.Pointer<wire_cst_adjacent_media> wireObj) {
    cst_api_fill_to_wire_adjacent_media(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_app_settings(
      AppSettings apiObj, ffi.Pointer<wire_cst_app_settings> wireObj) {
    cst_api_fill_to_wire_app_settings(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_media_item(
      MediaItem apiObj, ffi.Pointer<wire_cst_media_item> wireObj) {
    cst_api_fill_to_wire_media_item(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_note(
      Note apiObj, ffi.Pointer<wire_cst_note> wireObj) {
    cst_api_fill_to_wire_note(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_search_filter(
      SearchFilter apiObj, ffi.Pointer<wire_cst_search_filter> wireObj) {
    cst_api_fill_to_wire_search_filter(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_breadcrumb_item(
      BreadcrumbItem apiObj, wire_cst_breadcrumb_item wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
  }

  @protected
  void cst_api_fill_to_wire_export_progress(
      ExportProgress apiObj, wire_cst_export_progress wireObj) {
    wireObj.total_files = cst_encode_i_32(apiObj.totalFiles);
    wireObj.processed_files = cst_encode_i_32(apiObj.processedFiles);
    wireObj.current_file = cst_encode_opt_String(apiObj.currentFile);
    wireObj.status = cst_encode_String(apiObj.status);
  }

  @protected
  void cst_api_fill_to_wire_import_progress(
      ImportProgress apiObj, wire_cst_import_progress wireObj) {
    wireObj.total_files = cst_encode_i_32(apiObj.totalFiles);
    wireObj.processed_files = cst_encode_i_32(apiObj.processedFiles);
    wireObj.current_phase = cst_encode_String(apiObj.currentPhase);
    wireObj.status = cst_encode_String(apiObj.status);
  }

  @protected
  void cst_api_fill_to_wire_media_item(
      MediaItem apiObj, wire_cst_media_item wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.original_name = cst_encode_String(apiObj.originalName);
    wireObj.storage_name = cst_encode_String(apiObj.storageName);
    wireObj.file_path = cst_encode_String(apiObj.filePath);
    wireObj.thumbnail_path = cst_encode_String(apiObj.thumbnailPath);
    wireObj.media_type = cst_encode_media_type(apiObj.mediaType);
    wireObj.mime_type = cst_encode_String(apiObj.mimeType);
    wireObj.size = cst_encode_i_64(apiObj.size);
    wireObj.width = cst_encode_opt_box_autoadd_i_32(apiObj.width);
    wireObj.height = cst_encode_opt_box_autoadd_i_32(apiObj.height);
    wireObj.duration = cst_encode_opt_box_autoadd_i_64(apiObj.duration);
    wireObj.sha256_hash = cst_encode_String(apiObj.sha256Hash);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
    wireObj.updated_at = cst_encode_i_64(apiObj.updatedAt);
  }

  @protected
  void cst_api_fill_to_wire_note(Note apiObj, wire_cst_note wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.media_id = cst_encode_String(apiObj.mediaId);
    wireObj.content = cst_encode_String(apiObj.content);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
    wireObj.updated_at = cst_encode_i_64(apiObj.updatedAt);
  }

  @protected
  void cst_api_fill_to_wire_scan_result(
      ScanResult apiObj, wire_cst_scan_result wireObj) {
    wireObj.imported_count = cst_encode_i_32(apiObj.importedCount);
    wireObj.duplicate_count = cst_encode_i_32(apiObj.duplicateCount);
    wireObj.failed_count = cst_encode_i_32(apiObj.failedCount);
    wireObj.media_items = cst_encode_list_media_item(apiObj.mediaItems);
  }

  @protected
  void cst_api_fill_to_wire_search_filter(
      SearchFilter apiObj, wire_cst_search_filter wireObj) {
    wireObj.query = cst_encode_opt_String(apiObj.query);
    wireObj.media_type = cst_encode_opt_String(apiObj.mediaType);
    wireObj.start_date = cst_encode_opt_box_autoadd_i_64(apiObj.startDate);
    wireObj.end_date = cst_encode_opt_box_autoadd_i_64(apiObj.endDate);
    wireObj.album_id = cst_encode_opt_String(apiObj.albumId);
    wireObj.tag_ids = cst_encode_opt_list_String(apiObj.tagIds);
    wireObj.tag_count = cst_encode_opt_box_autoadd_i_32(apiObj.tagCount);
  }

  @protected
  void cst_api_fill_to_wire_storage_stats(
      StorageStats apiObj, wire_cst_storage_stats wireObj) {
    wireObj.total_media_count = cst_encode_i_32(apiObj.totalMediaCount);
    wireObj.total_size = cst_encode_i_64(apiObj.totalSize);
    wireObj.thumbnail_cache_size = cst_encode_i_64(apiObj.thumbnailCacheSize);
    wireObj.database_size = cst_encode_i_64(apiObj.databaseSize);
  }

  @protected
  void cst_api_fill_to_wire_tag(Tag apiObj, wire_cst_tag wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.color = cst_encode_opt_String(apiObj.color);
    wireObj.parent_id = cst_encode_opt_String(apiObj.parentId);
    wireObj.created_at = cst_encode_i_64(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_tag_breadcrumb(
      TagBreadcrumb apiObj, wire_cst_tag_breadcrumb wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
  }

  @protected
  void cst_api_fill_to_wire_tag_with_info(
      TagWithInfo apiObj, wire_cst_tag_with_info wireObj) {
    cst_api_fill_to_wire_tag(apiObj.tag, wireObj.tag);
    wireObj.media_count = cst_encode_i_32(apiObj.mediaCount);
    wireObj.cover_thumbnail_path =
        cst_encode_opt_String(apiObj.coverThumbnailPath);
    wireObj.has_children = cst_encode_i_32(apiObj.hasChildren);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_conflict_strategy(ConflictStrategy raw);

  @protected
  int cst_encode_filter_mode(FilterMode raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_language_setting(LanguageSetting raw);

  @protected
  int cst_encode_media_type(MediaType raw);

  @protected
  int cst_encode_theme_mode(ThemeMode raw);

  @protected
  int cst_encode_theme_mode_setting(ThemeModeSetting raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_adjacent_media(AdjacentMedia self, SseSerializer serializer);

  @protected
  void sse_encode_album(Album self, SseSerializer serializer);

  @protected
  void sse_encode_album_with_info(AlbumWithInfo self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_adjacent_media(
      AdjacentMedia self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
      AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_item(
      MediaItem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_filter(
      SearchFilter self, SseSerializer serializer);

  @protected
  void sse_encode_breadcrumb_item(
      BreadcrumbItem self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_strategy(
      ConflictStrategy self, SseSerializer serializer);

  @protected
  void sse_encode_export_progress(
      ExportProgress self, SseSerializer serializer);

  @protected
  void sse_encode_filter_mode(FilterMode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_progress(
      ImportProgress self, SseSerializer serializer);

  @protected
  void sse_encode_language_setting(
      LanguageSetting self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_with_info(
      List<AlbumWithInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_breadcrumb_item(
      List<BreadcrumbItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_item(
      List<MediaItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_breadcrumb(
      List<TagBreadcrumb> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_with_info(
      List<TagWithInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_media_item(MediaItem self, SseSerializer serializer);

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer);

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_adjacent_media(
      AdjacentMedia? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_item(
      MediaItem? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_note(Note? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_scan_result(ScanResult self, SseSerializer serializer);

  @protected
  void sse_encode_search_filter(SearchFilter self, SseSerializer serializer);

  @protected
  void sse_encode_storage_stats(StorageStats self, SseSerializer serializer);

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_tag_breadcrumb(TagBreadcrumb self, SseSerializer serializer);

  @protected
  void sse_encode_tag_with_info(TagWithInfo self, SseSerializer serializer);

  @protected
  void sse_encode_theme_mode(ThemeMode self, SseSerializer serializer);

  @protected
  void sse_encode_theme_mode_setting(
      ThemeModeSetting self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__album__add_media_to_album(
    int port_,
    ffi.Pointer<wire_cst_list_String> media_ids,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> album_id,
  ) {
    return _wire__crate__api__album__add_media_to_album(
      port_,
      media_ids,
      album_id,
    );
  }

  late final _wire__crate__api__album__add_media_to_albumPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__add_media_to_album');
  late final _wire__crate__api__album__add_media_to_album =
      _wire__crate__api__album__add_media_to_albumPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_String>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__add_tag_to_media(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> media_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tag_id,
  ) {
    return _wire__crate__api__tag__add_tag_to_media(
      port_,
      media_id,
      tag_id,
    );
  }

  late final _wire__crate__api__tag__add_tag_to_mediaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__add_tag_to_media');
  late final _wire__crate__api__tag__add_tag_to_media =
      _wire__crate__api__tag__add_tag_to_mediaPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__media__batch_delete_media(
    int port_,
    ffi.Pointer<wire_cst_list_String> ids,
  ) {
    return _wire__crate__api__media__batch_delete_media(
      port_,
      ids,
    );
  }

  late final _wire__crate__api__media__batch_delete_mediaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__batch_delete_media');
  late final _wire__crate__api__media__batch_delete_media =
      _wire__crate__api__media__batch_delete_mediaPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_list_String>)>();

  void wire__crate__api__scanner__calculate_file_hash(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
  ) {
    return _wire__crate__api__scanner__calculate_file_hash(
      port_,
      file_path,
    );
  }

  late final _wire__crate__api__scanner__calculate_file_hashPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__scanner__calculate_file_hash');
  late final _wire__crate__api__scanner__calculate_file_hash =
      _wire__crate__api__scanner__calculate_file_hashPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__settings__clear_thumbnail_cache(
    int port_,
  ) {
    return _wire__crate__api__settings__clear_thumbnail_cache(
      port_,
    );
  }

  late final _wire__crate__api__settings__clear_thumbnail_cachePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__clear_thumbnail_cache');
  late final _wire__crate__api__settings__clear_thumbnail_cache =
      _wire__crate__api__settings__clear_thumbnail_cachePtr
          .asFunction<void Function(int)>();

  void wire__crate__api__album__create_album(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id,
  ) {
    return _wire__crate__api__album__create_album(
      port_,
      name,
      parent_id,
    );
  }

  late final _wire__crate__api__album__create_albumPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__create_album');
  late final _wire__crate__api__album__create_album =
      _wire__crate__api__album__create_albumPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__create_tag(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> color,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id,
  ) {
    return _wire__crate__api__tag__create_tag(
      port_,
      name,
      color,
      parent_id,
    );
  }

  late final _wire__crate__api__tag__create_tagPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__create_tag');
  late final _wire__crate__api__tag__create_tag =
      _wire__crate__api__tag__create_tagPtr.asFunction<
          void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__album__delete_album(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__album__delete_album(
      port_,
      id,
    );
  }

  late final _wire__crate__api__album__delete_albumPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__delete_album');
  late final _wire__crate__api__album__delete_album =
      _wire__crate__api__album__delete_albumPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__settings__delete_all_data(
    int port_,
  ) {
    return _wire__crate__api__settings__delete_all_data(
      port_,
    );
  }

  late final _wire__crate__api__settings__delete_all_dataPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__delete_all_data');
  late final _wire__crate__api__settings__delete_all_data =
      _wire__crate__api__settings__delete_all_dataPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__media__delete_media(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__media__delete_media(
      port_,
      id,
    );
  }

  late final _wire__crate__api__media__delete_mediaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__delete_media');
  late final _wire__crate__api__media__delete_media =
      _wire__crate__api__media__delete_mediaPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__note__delete_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__note__delete_note(
      port_,
      id,
    );
  }

  late final _wire__crate__api__note__delete_notePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__note__delete_note');
  late final _wire__crate__api__note__delete_note =
      _wire__crate__api__note__delete_notePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__delete_tag(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__tag__delete_tag(
      port_,
      id,
    );
  }

  late final _wire__crate__api__tag__delete_tagPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__delete_tag');
  late final _wire__crate__api__tag__delete_tag =
      _wire__crate__api__tag__delete_tagPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__settings__delete_unreferenced_files(
    int port_,
  ) {
    return _wire__crate__api__settings__delete_unreferenced_files(
      port_,
    );
  }

  late final _wire__crate__api__settings__delete_unreferenced_filesPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__delete_unreferenced_files');
  late final _wire__crate__api__settings__delete_unreferenced_files =
      _wire__crate__api__settings__delete_unreferenced_filesPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__album__ensure_default_album(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
  ) {
    return _wire__crate__api__album__ensure_default_album(
      port_,
      name,
    );
  }

  late final _wire__crate__api__album__ensure_default_albumPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__ensure_default_album');
  late final _wire__crate__api__album__ensure_default_album =
      _wire__crate__api__album__ensure_default_albumPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__ensure_default_tag(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> color,
  ) {
    return _wire__crate__api__tag__ensure_default_tag(
      port_,
      name,
      color,
    );
  }

  late final _wire__crate__api__tag__ensure_default_tagPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__ensure_default_tag');
  late final _wire__crate__api__tag__ensure_default_tag =
      _wire__crate__api__tag__ensure_default_tagPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__settings__export_data(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> export_path,
  ) {
    return _wire__crate__api__settings__export_data(
      port_,
      export_path,
    );
  }

  late final _wire__crate__api__settings__export_dataPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__export_data');
  late final _wire__crate__api__settings__export_data =
      _wire__crate__api__settings__export_dataPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__import_export__export_package(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> export_path,
    bool include_media,
  ) {
    return _wire__crate__api__import_export__export_package(
      port_,
      export_path,
      include_media,
    );
  }

  late final _wire__crate__api__import_export__export_packagePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>, ffi.Bool)>>(
      'frbgen_advance_media_kb_wire__crate__api__import_export__export_package');
  late final _wire__crate__api__import_export__export_package =
      _wire__crate__api__import_export__export_packagePtr.asFunction<
          void Function(
              int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, bool)>();

  void wire__crate__api__import_export__export_to_download(
    int port_,
    ffi.Pointer<wire_cst_list_String> media_ids,
  ) {
    return _wire__crate__api__import_export__export_to_download(
      port_,
      media_ids,
    );
  }

  late final _wire__crate__api__import_export__export_to_downloadPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>)>>(
      'frbgen_advance_media_kb_wire__crate__api__import_export__export_to_download');
  late final _wire__crate__api__import_export__export_to_download =
      _wire__crate__api__import_export__export_to_downloadPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_list_String>)>();

  void wire__crate__api__media__filter_media_by_type(
    int port_,
    int media_type,
  ) {
    return _wire__crate__api__media__filter_media_by_type(
      port_,
      media_type,
    );
  }

  late final _wire__crate__api__media__filter_media_by_typePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__filter_media_by_type');
  late final _wire__crate__api__media__filter_media_by_type =
      _wire__crate__api__media__filter_media_by_typePtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__enums__filter_mode_as_str(
    int port_,
    int that,
  ) {
    return _wire__crate__api__enums__filter_mode_as_str(
      port_,
      that,
    );
  }

  late final _wire__crate__api__enums__filter_mode_as_strPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__enums__filter_mode_as_str');
  late final _wire__crate__api__enums__filter_mode_as_str =
      _wire__crate__api__enums__filter_mode_as_strPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__enums__filter_mode_display_name(
    int port_,
    int that,
  ) {
    return _wire__crate__api__enums__filter_mode_display_name(
      port_,
      that,
    );
  }

  late final _wire__crate__api__enums__filter_mode_display_namePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__enums__filter_mode_display_name');
  late final _wire__crate__api__enums__filter_mode_display_name =
      _wire__crate__api__enums__filter_mode_display_namePtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__settings__find_unreferenced_files(
    int port_,
  ) {
    return _wire__crate__api__settings__find_unreferenced_files(
      port_,
    );
  }

  late final _wire__crate__api__settings__find_unreferenced_filesPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__find_unreferenced_files');
  late final _wire__crate__api__settings__find_unreferenced_files =
      _wire__crate__api__settings__find_unreferenced_filesPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__scanner__generate_thumbnail(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
    int quality,
  ) {
    return _wire__crate__api__scanner__generate_thumbnail(
      port_,
      file_path,
      quality,
    );
  }

  late final _wire__crate__api__scanner__generate_thumbnailPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__scanner__generate_thumbnail');
  late final _wire__crate__api__scanner__generate_thumbnail =
      _wire__crate__api__scanner__generate_thumbnailPtr.asFunction<
          void Function(
              int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, int)>();

  void wire__crate__api__media__get_adjacent_media(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__media__get_adjacent_media(
      port_,
      id,
    );
  }

  late final _wire__crate__api__media__get_adjacent_mediaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__get_adjacent_media');
  late final _wire__crate__api__media__get_adjacent_media =
      _wire__crate__api__media__get_adjacent_mediaPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__album__get_album_breadcrumb(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> album_id,
  ) {
    return _wire__crate__api__album__get_album_breadcrumb(
      port_,
      album_id,
    );
  }

  late final _wire__crate__api__album__get_album_breadcrumbPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__get_album_breadcrumb');
  late final _wire__crate__api__album__get_album_breadcrumb =
      _wire__crate__api__album__get_album_breadcrumbPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__media__get_all_media(
    int port_,
  ) {
    return _wire__crate__api__media__get_all_media(
      port_,
    );
  }

  late final _wire__crate__api__media__get_all_mediaPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_advance_media_kb_wire__crate__api__media__get_all_media');
  late final _wire__crate__api__media__get_all_media =
      _wire__crate__api__media__get_all_mediaPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__note__get_all_notes(
    int port_,
  ) {
    return _wire__crate__api__note__get_all_notes(
      port_,
    );
  }

  late final _wire__crate__api__note__get_all_notesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_advance_media_kb_wire__crate__api__note__get_all_notes');
  late final _wire__crate__api__note__get_all_notes =
      _wire__crate__api__note__get_all_notesPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__tag__get_all_tags(
    int port_,
  ) {
    return _wire__crate__api__tag__get_all_tags(
      port_,
    );
  }

  late final _wire__crate__api__tag__get_all_tagsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_advance_media_kb_wire__crate__api__tag__get_all_tags');
  late final _wire__crate__api__tag__get_all_tags =
      _wire__crate__api__tag__get_all_tagsPtr.asFunction<void Function(int)>();

  void wire__crate__api__album__get_child_albums(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id,
  ) {
    return _wire__crate__api__album__get_child_albums(
      port_,
      parent_id,
    );
  }

  late final _wire__crate__api__album__get_child_albumsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__get_child_albums');
  late final _wire__crate__api__album__get_child_albums =
      _wire__crate__api__album__get_child_albumsPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__get_child_tags(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id,
  ) {
    return _wire__crate__api__tag__get_child_tags(
      port_,
      parent_id,
    );
  }

  late final _wire__crate__api__tag__get_child_tagsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__get_child_tags');
  late final _wire__crate__api__tag__get_child_tags =
      _wire__crate__api__tag__get_child_tagsPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__album__get_media_by_album(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> album_id,
  ) {
    return _wire__crate__api__album__get_media_by_album(
      port_,
      album_id,
    );
  }

  late final _wire__crate__api__album__get_media_by_albumPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__get_media_by_album');
  late final _wire__crate__api__album__get_media_by_album =
      _wire__crate__api__album__get_media_by_albumPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__media__get_media_by_filter(
    int port_,
    int filter,
  ) {
    return _wire__crate__api__media__get_media_by_filter(
      port_,
      filter,
    );
  }

  late final _wire__crate__api__media__get_media_by_filterPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__get_media_by_filter');
  late final _wire__crate__api__media__get_media_by_filter =
      _wire__crate__api__media__get_media_by_filterPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__media__get_media_by_id(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__media__get_media_by_id(
      port_,
      id,
    );
  }

  late final _wire__crate__api__media__get_media_by_idPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__get_media_by_id');
  late final _wire__crate__api__media__get_media_by_id =
      _wire__crate__api__media__get_media_by_idPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__get_media_by_tag(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tag_id,
  ) {
    return _wire__crate__api__tag__get_media_by_tag(
      port_,
      tag_id,
    );
  }

  late final _wire__crate__api__tag__get_media_by_tagPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__get_media_by_tag');
  late final _wire__crate__api__tag__get_media_by_tag =
      _wire__crate__api__tag__get_media_by_tagPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__get_media_by_tags_and(
    int port_,
    ffi.Pointer<wire_cst_list_String> tag_ids,
  ) {
    return _wire__crate__api__tag__get_media_by_tags_and(
      port_,
      tag_ids,
    );
  }

  late final _wire__crate__api__tag__get_media_by_tags_andPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__get_media_by_tags_and');
  late final _wire__crate__api__tag__get_media_by_tags_and =
      _wire__crate__api__tag__get_media_by_tags_andPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_list_String>)>();

  void wire__crate__api__tag__get_media_by_tags_or(
    int port_,
    ffi.Pointer<wire_cst_list_String> tag_ids,
  ) {
    return _wire__crate__api__tag__get_media_by_tags_or(
      port_,
      tag_ids,
    );
  }

  late final _wire__crate__api__tag__get_media_by_tags_orPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__get_media_by_tags_or');
  late final _wire__crate__api__tag__get_media_by_tags_or =
      _wire__crate__api__tag__get_media_by_tags_orPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_list_String>)>();

  void wire__crate__api__tag__get_media_tags(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> media_id,
  ) {
    return _wire__crate__api__tag__get_media_tags(
      port_,
      media_id,
    );
  }

  late final _wire__crate__api__tag__get_media_tagsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__get_media_tags');
  late final _wire__crate__api__tag__get_media_tags =
      _wire__crate__api__tag__get_media_tagsPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__search__get_media_with_any_album(
    int port_,
  ) {
    return _wire__crate__api__search__get_media_with_any_album(
      port_,
    );
  }

  late final _wire__crate__api__search__get_media_with_any_albumPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__search__get_media_with_any_album');
  late final _wire__crate__api__search__get_media_with_any_album =
      _wire__crate__api__search__get_media_with_any_albumPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__search__get_media_with_any_tag(
    int port_,
  ) {
    return _wire__crate__api__search__get_media_with_any_tag(
      port_,
    );
  }

  late final _wire__crate__api__search__get_media_with_any_tagPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__search__get_media_with_any_tag');
  late final _wire__crate__api__search__get_media_with_any_tag =
      _wire__crate__api__search__get_media_with_any_tagPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__media__get_media_with_tags(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__media__get_media_with_tags(
      port_,
      id,
    );
  }

  late final _wire__crate__api__media__get_media_with_tagsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__get_media_with_tags');
  late final _wire__crate__api__media__get_media_with_tags =
      _wire__crate__api__media__get_media_with_tagsPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__search__get_media_without_any_album(
    int port_,
  ) {
    return _wire__crate__api__search__get_media_without_any_album(
      port_,
    );
  }

  late final _wire__crate__api__search__get_media_without_any_albumPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__search__get_media_without_any_album');
  late final _wire__crate__api__search__get_media_without_any_album =
      _wire__crate__api__search__get_media_without_any_albumPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__search__get_media_without_any_tag(
    int port_,
  ) {
    return _wire__crate__api__search__get_media_without_any_tag(
      port_,
    );
  }

  late final _wire__crate__api__search__get_media_without_any_tagPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__search__get_media_without_any_tag');
  late final _wire__crate__api__search__get_media_without_any_tag =
      _wire__crate__api__search__get_media_without_any_tagPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__note__get_note_by_id(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__note__get_note_by_id(
      port_,
      id,
    );
  }

  late final _wire__crate__api__note__get_note_by_idPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__note__get_note_by_id');
  late final _wire__crate__api__note__get_note_by_id =
      _wire__crate__api__note__get_note_by_idPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__note__get_note_by_media_id(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> media_id,
  ) {
    return _wire__crate__api__note__get_note_by_media_id(
      port_,
      media_id,
    );
  }

  late final _wire__crate__api__note__get_note_by_media_idPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__note__get_note_by_media_id');
  late final _wire__crate__api__note__get_note_by_media_id =
      _wire__crate__api__note__get_note_by_media_idPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__album__get_root_albums(
    int port_,
  ) {
    return _wire__crate__api__album__get_root_albums(
      port_,
    );
  }

  late final _wire__crate__api__album__get_root_albumsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_advance_media_kb_wire__crate__api__album__get_root_albums');
  late final _wire__crate__api__album__get_root_albums =
      _wire__crate__api__album__get_root_albumsPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__tag__get_root_tags(
    int port_,
  ) {
    return _wire__crate__api__tag__get_root_tags(
      port_,
    );
  }

  late final _wire__crate__api__tag__get_root_tagsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_advance_media_kb_wire__crate__api__tag__get_root_tags');
  late final _wire__crate__api__tag__get_root_tags =
      _wire__crate__api__tag__get_root_tagsPtr.asFunction<void Function(int)>();

  void wire__crate__api__settings__get_settings(
    int port_,
  ) {
    return _wire__crate__api__settings__get_settings(
      port_,
    );
  }

  late final _wire__crate__api__settings__get_settingsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_advance_media_kb_wire__crate__api__settings__get_settings');
  late final _wire__crate__api__settings__get_settings =
      _wire__crate__api__settings__get_settingsPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__settings__get_storage_stats(
    int port_,
  ) {
    return _wire__crate__api__settings__get_storage_stats(
      port_,
    );
  }

  late final _wire__crate__api__settings__get_storage_statsPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__get_storage_stats');
  late final _wire__crate__api__settings__get_storage_stats =
      _wire__crate__api__settings__get_storage_statsPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__scanner__get_supported_extensions(
    int port_,
  ) {
    return _wire__crate__api__scanner__get_supported_extensions(
      port_,
    );
  }

  late final _wire__crate__api__scanner__get_supported_extensionsPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__scanner__get_supported_extensions');
  late final _wire__crate__api__scanner__get_supported_extensions =
      _wire__crate__api__scanner__get_supported_extensionsPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__tag__get_tag_breadcrumb(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tag_id,
  ) {
    return _wire__crate__api__tag__get_tag_breadcrumb(
      port_,
      tag_id,
    );
  }

  late final _wire__crate__api__tag__get_tag_breadcrumbPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__get_tag_breadcrumb');
  late final _wire__crate__api__tag__get_tag_breadcrumb =
      _wire__crate__api__tag__get_tag_breadcrumbPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__settings__import_data(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> import_path,
  ) {
    return _wire__crate__api__settings__import_data(
      port_,
      import_path,
    );
  }

  late final _wire__crate__api__settings__import_dataPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__import_data');
  late final _wire__crate__api__settings__import_data =
      _wire__crate__api__settings__import_dataPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__import_export__import_package(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> package_path,
    int conflict_strategy,
  ) {
    return _wire__crate__api__import_export__import_package(
      port_,
      package_path,
      conflict_strategy,
    );
  }

  late final _wire__crate__api__import_export__import_packagePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__import_export__import_package');
  late final _wire__crate__api__import_export__import_package =
      _wire__crate__api__import_export__import_packagePtr.asFunction<
          void Function(
              int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, int)>();

  void wire__crate__api__scanner__import_single_file(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
  ) {
    return _wire__crate__api__scanner__import_single_file(
      port_,
      file_path,
    );
  }

  late final _wire__crate__api__scanner__import_single_filePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__scanner__import_single_file');
  late final _wire__crate__api__scanner__import_single_file =
      _wire__crate__api__scanner__import_single_filePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__settings__init_app(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> app_dir,
  ) {
    return _wire__crate__api__settings__init_app(
      port_,
      app_dir,
    );
  }

  late final _wire__crate__api__settings__init_appPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__init_app');
  late final _wire__crate__api__settings__init_app =
      _wire__crate__api__settings__init_appPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__scanner__is_hash_exists(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> hash,
  ) {
    return _wire__crate__api__scanner__is_hash_exists(
      port_,
      hash,
    );
  }

  late final _wire__crate__api__scanner__is_hash_existsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__scanner__is_hash_exists');
  late final _wire__crate__api__scanner__is_hash_exists =
      _wire__crate__api__scanner__is_hash_existsPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__enums__language_setting_as_str(
    int port_,
    int that,
  ) {
    return _wire__crate__api__enums__language_setting_as_str(
      port_,
      that,
    );
  }

  late final _wire__crate__api__enums__language_setting_as_strPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__enums__language_setting_as_str');
  late final _wire__crate__api__enums__language_setting_as_str =
      _wire__crate__api__enums__language_setting_as_strPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__enums__language_setting_from_str(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> s,
  ) {
    return _wire__crate__api__enums__language_setting_from_str(
      port_,
      s,
    );
  }

  late final _wire__crate__api__enums__language_setting_from_strPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__enums__language_setting_from_str');
  late final _wire__crate__api__enums__language_setting_from_str =
      _wire__crate__api__enums__language_setting_from_strPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__media__media_type_as_i32(
    int port_,
    int that,
  ) {
    return _wire__crate__api__media__media_type_as_i32(
      port_,
      that,
    );
  }

  late final _wire__crate__api__media__media_type_as_i32Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'frbgen_advance_media_kb_wire__crate__api__media__media_type_as_i32');
  late final _wire__crate__api__media__media_type_as_i32 =
      _wire__crate__api__media__media_type_as_i32Ptr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__media__media_type_as_str(
    int port_,
    int that,
  ) {
    return _wire__crate__api__media__media_type_as_str(
      port_,
      that,
    );
  }

  late final _wire__crate__api__media__media_type_as_strPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'frbgen_advance_media_kb_wire__crate__api__media__media_type_as_str');
  late final _wire__crate__api__media__media_type_as_str =
      _wire__crate__api__media__media_type_as_strPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__media__media_type_from_str(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> s,
  ) {
    return _wire__crate__api__media__media_type_from_str(
      port_,
      s,
    );
  }

  late final _wire__crate__api__media__media_type_from_strPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__media_type_from_str');
  late final _wire__crate__api__media__media_type_from_str =
      _wire__crate__api__media__media_type_from_strPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__album__remove_media_from_album(
    int port_,
    ffi.Pointer<wire_cst_list_String> media_ids,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> album_id,
  ) {
    return _wire__crate__api__album__remove_media_from_album(
      port_,
      media_ids,
      album_id,
    );
  }

  late final _wire__crate__api__album__remove_media_from_albumPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__remove_media_from_album');
  late final _wire__crate__api__album__remove_media_from_album =
      _wire__crate__api__album__remove_media_from_albumPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_String>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__remove_tag_from_media(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> media_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tag_id,
  ) {
    return _wire__crate__api__tag__remove_tag_from_media(
      port_,
      media_id,
      tag_id,
    );
  }

  late final _wire__crate__api__tag__remove_tag_from_mediaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__remove_tag_from_media');
  late final _wire__crate__api__tag__remove_tag_from_media =
      _wire__crate__api__tag__remove_tag_from_mediaPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__album__rename_album(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_name,
  ) {
    return _wire__crate__api__album__rename_album(
      port_,
      id,
      new_name,
    );
  }

  late final _wire__crate__api__album__rename_albumPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__rename_album');
  late final _wire__crate__api__album__rename_album =
      _wire__crate__api__album__rename_albumPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__rename_tag(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_name,
  ) {
    return _wire__crate__api__tag__rename_tag(
      port_,
      id,
      new_name,
    );
  }

  late final _wire__crate__api__tag__rename_tagPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__rename_tag');
  late final _wire__crate__api__tag__rename_tag =
      _wire__crate__api__tag__rename_tagPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__note__save_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> media_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
  ) {
    return _wire__crate__api__note__save_note(
      port_,
      media_id,
      content,
    );
  }

  late final _wire__crate__api__note__save_notePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__note__save_note');
  late final _wire__crate__api__note__save_note =
      _wire__crate__api__note__save_notePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__settings__save_settings(
    int port_,
    ffi.Pointer<wire_cst_app_settings> settings,
  ) {
    return _wire__crate__api__settings__save_settings(
      port_,
      settings,
    );
  }

  late final _wire__crate__api__settings__save_settingsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_app_settings>)>>(
      'frbgen_advance_media_kb_wire__crate__api__settings__save_settings');
  late final _wire__crate__api__settings__save_settings =
      _wire__crate__api__settings__save_settingsPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_app_settings>)>();

  void wire__crate__api__scanner__scan_directory(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__scanner__scan_directory(
      port_,
      path,
    );
  }

  late final _wire__crate__api__scanner__scan_directoryPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__scanner__scan_directory');
  late final _wire__crate__api__scanner__scan_directory =
      _wire__crate__api__scanner__scan_directoryPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__search__search_filter_default(
    int port_,
  ) {
    return _wire__crate__api__search__search_filter_default(
      port_,
    );
  }

  late final _wire__crate__api__search__search_filter_defaultPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
      'frbgen_advance_media_kb_wire__crate__api__search__search_filter_default');
  late final _wire__crate__api__search__search_filter_default =
      _wire__crate__api__search__search_filter_defaultPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__media__search_media(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> query,
  ) {
    return _wire__crate__api__media__search_media(
      port_,
      query,
    );
  }

  late final _wire__crate__api__media__search_mediaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__search_media');
  late final _wire__crate__api__media__search_media =
      _wire__crate__api__media__search_mediaPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__search__search_media_advanced(
    int port_,
    ffi.Pointer<wire_cst_search_filter> filter,
  ) {
    return _wire__crate__api__search__search_media_advanced(
      port_,
      filter,
    );
  }

  late final _wire__crate__api__search__search_media_advancedPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_search_filter>)>>(
      'frbgen_advance_media_kb_wire__crate__api__search__search_media_advanced');
  late final _wire__crate__api__search__search_media_advanced =
      _wire__crate__api__search__search_media_advancedPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_search_filter>)>();

  void wire__crate__api__album__set_album_cover(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> album_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> media_id,
  ) {
    return _wire__crate__api__album__set_album_cover(
      port_,
      album_id,
      media_id,
    );
  }

  late final _wire__crate__api__album__set_album_coverPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__album__set_album_cover');
  late final _wire__crate__api__album__set_album_cover =
      _wire__crate__api__album__set_album_coverPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__enums__theme_mode_setting_as_str(
    int port_,
    int that,
  ) {
    return _wire__crate__api__enums__theme_mode_setting_as_str(
      port_,
      that,
    );
  }

  late final _wire__crate__api__enums__theme_mode_setting_as_strPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
      'frbgen_advance_media_kb_wire__crate__api__enums__theme_mode_setting_as_str');
  late final _wire__crate__api__enums__theme_mode_setting_as_str =
      _wire__crate__api__enums__theme_mode_setting_as_strPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__enums__theme_mode_setting_from_str(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> s,
  ) {
    return _wire__crate__api__enums__theme_mode_setting_from_str(
      port_,
      s,
    );
  }

  late final _wire__crate__api__enums__theme_mode_setting_from_strPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__enums__theme_mode_setting_from_str');
  late final _wire__crate__api__enums__theme_mode_setting_from_str =
      _wire__crate__api__enums__theme_mode_setting_from_strPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__media__update_media(
    int port_,
    ffi.Pointer<wire_cst_media_item> media,
  ) {
    return _wire__crate__api__media__update_media(
      port_,
      media,
    );
  }

  late final _wire__crate__api__media__update_mediaPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_media_item>)>>(
      'frbgen_advance_media_kb_wire__crate__api__media__update_media');
  late final _wire__crate__api__media__update_media =
      _wire__crate__api__media__update_mediaPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_media_item>)>();

  void wire__crate__api__tag__update_tag_color(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> color,
  ) {
    return _wire__crate__api__tag__update_tag_color(
      port_,
      id,
      color,
    );
  }

  late final _wire__crate__api__tag__update_tag_colorPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__update_tag_color');
  late final _wire__crate__api__tag__update_tag_color =
      _wire__crate__api__tag__update_tag_colorPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__tag__update_tag_parent(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id,
  ) {
    return _wire__crate__api__tag__update_tag_parent(
      port_,
      id,
      parent_id,
    );
  }

  late final _wire__crate__api__tag__update_tag_parentPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_advance_media_kb_wire__crate__api__tag__update_tag_parent');
  late final _wire__crate__api__tag__update_tag_parent =
      _wire__crate__api__tag__update_tag_parentPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  ffi.Pointer<wire_cst_adjacent_media> cst_new_box_autoadd_adjacent_media() {
    return _cst_new_box_autoadd_adjacent_media();
  }

  late final _cst_new_box_autoadd_adjacent_mediaPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_adjacent_media> Function()>>(
      'frbgen_advance_media_kb_cst_new_box_autoadd_adjacent_media');
  late final _cst_new_box_autoadd_adjacent_media =
      _cst_new_box_autoadd_adjacent_mediaPtr
          .asFunction<ffi.Pointer<wire_cst_adjacent_media> Function()>();

  ffi.Pointer<wire_cst_app_settings> cst_new_box_autoadd_app_settings() {
    return _cst_new_box_autoadd_app_settings();
  }

  late final _cst_new_box_autoadd_app_settingsPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_app_settings> Function()>>(
      'frbgen_advance_media_kb_cst_new_box_autoadd_app_settings');
  late final _cst_new_box_autoadd_app_settings =
      _cst_new_box_autoadd_app_settingsPtr
          .asFunction<ffi.Pointer<wire_cst_app_settings> Function()>();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_i_32(
    int value,
  ) {
    return _cst_new_box_autoadd_i_32(
      value,
    );
  }

  late final _cst_new_box_autoadd_i_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
          'frbgen_advance_media_kb_cst_new_box_autoadd_i_32');
  late final _cst_new_box_autoadd_i_32 = _cst_new_box_autoadd_i_32Ptr
      .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(
    int value,
  ) {
    return _cst_new_box_autoadd_i_64(
      value,
    );
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
          'frbgen_advance_media_kb_cst_new_box_autoadd_i_64');
  late final _cst_new_box_autoadd_i_64 = _cst_new_box_autoadd_i_64Ptr
      .asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<wire_cst_media_item> cst_new_box_autoadd_media_item() {
    return _cst_new_box_autoadd_media_item();
  }

  late final _cst_new_box_autoadd_media_itemPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_media_item> Function()>>(
          'frbgen_advance_media_kb_cst_new_box_autoadd_media_item');
  late final _cst_new_box_autoadd_media_item =
      _cst_new_box_autoadd_media_itemPtr
          .asFunction<ffi.Pointer<wire_cst_media_item> Function()>();

  ffi.Pointer<wire_cst_note> cst_new_box_autoadd_note() {
    return _cst_new_box_autoadd_note();
  }

  late final _cst_new_box_autoadd_notePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_note> Function()>>(
          'frbgen_advance_media_kb_cst_new_box_autoadd_note');
  late final _cst_new_box_autoadd_note = _cst_new_box_autoadd_notePtr
      .asFunction<ffi.Pointer<wire_cst_note> Function()>();

  ffi.Pointer<wire_cst_search_filter> cst_new_box_autoadd_search_filter() {
    return _cst_new_box_autoadd_search_filter();
  }

  late final _cst_new_box_autoadd_search_filterPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_search_filter> Function()>>(
      'frbgen_advance_media_kb_cst_new_box_autoadd_search_filter');
  late final _cst_new_box_autoadd_search_filter =
      _cst_new_box_autoadd_search_filterPtr
          .asFunction<ffi.Pointer<wire_cst_search_filter> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(
    int len,
  ) {
    return _cst_new_list_String(
      len,
    );
  }

  late final _cst_new_list_StringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(
              ffi.Int32)>>('frbgen_advance_media_kb_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_album_with_info> cst_new_list_album_with_info(
    int len,
  ) {
    return _cst_new_list_album_with_info(
      len,
    );
  }

  late final _cst_new_list_album_with_infoPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_album_with_info> Function(ffi.Int32)>>(
      'frbgen_advance_media_kb_cst_new_list_album_with_info');
  late final _cst_new_list_album_with_info = _cst_new_list_album_with_infoPtr
      .asFunction<ffi.Pointer<wire_cst_list_album_with_info> Function(int)>();

  ffi.Pointer<wire_cst_list_breadcrumb_item> cst_new_list_breadcrumb_item(
    int len,
  ) {
    return _cst_new_list_breadcrumb_item(
      len,
    );
  }

  late final _cst_new_list_breadcrumb_itemPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_breadcrumb_item> Function(ffi.Int32)>>(
      'frbgen_advance_media_kb_cst_new_list_breadcrumb_item');
  late final _cst_new_list_breadcrumb_item = _cst_new_list_breadcrumb_itemPtr
      .asFunction<ffi.Pointer<wire_cst_list_breadcrumb_item> Function(int)>();

  ffi.Pointer<wire_cst_list_media_item> cst_new_list_media_item(
    int len,
  ) {
    return _cst_new_list_media_item(
      len,
    );
  }

  late final _cst_new_list_media_itemPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_media_item> Function(
              ffi.Int32)>>('frbgen_advance_media_kb_cst_new_list_media_item');
  late final _cst_new_list_media_item = _cst_new_list_media_itemPtr
      .asFunction<ffi.Pointer<wire_cst_list_media_item> Function(int)>();

  ffi.Pointer<wire_cst_list_note> cst_new_list_note(
    int len,
  ) {
    return _cst_new_list_note(
      len,
    );
  }

  late final _cst_new_list_notePtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_list_note> Function(ffi.Int32)>>(
      'frbgen_advance_media_kb_cst_new_list_note');
  late final _cst_new_list_note = _cst_new_list_notePtr
      .asFunction<ffi.Pointer<wire_cst_list_note> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)>>(
      'frbgen_advance_media_kb_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_tag> cst_new_list_tag(
    int len,
  ) {
    return _cst_new_list_tag(
      len,
    );
  }

  late final _cst_new_list_tagPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_list_tag> Function(ffi.Int32)>>(
      'frbgen_advance_media_kb_cst_new_list_tag');
  late final _cst_new_list_tag = _cst_new_list_tagPtr
      .asFunction<ffi.Pointer<wire_cst_list_tag> Function(int)>();

  ffi.Pointer<wire_cst_list_tag_breadcrumb> cst_new_list_tag_breadcrumb(
    int len,
  ) {
    return _cst_new_list_tag_breadcrumb(
      len,
    );
  }

  late final _cst_new_list_tag_breadcrumbPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_tag_breadcrumb> Function(ffi.Int32)>>(
      'frbgen_advance_media_kb_cst_new_list_tag_breadcrumb');
  late final _cst_new_list_tag_breadcrumb = _cst_new_list_tag_breadcrumbPtr
      .asFunction<ffi.Pointer<wire_cst_list_tag_breadcrumb> Function(int)>();

  ffi.Pointer<wire_cst_list_tag_with_info> cst_new_list_tag_with_info(
    int len,
  ) {
    return _cst_new_list_tag_with_info(
      len,
    );
  }

  late final _cst_new_list_tag_with_infoPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_tag_with_info> Function(ffi.Int32)>>(
      'frbgen_advance_media_kb_cst_new_list_tag_with_info');
  late final _cst_new_list_tag_with_info = _cst_new_list_tag_with_infoPtr
      .asFunction<ffi.Pointer<wire_cst_list_tag_with_info> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_app_settings extends ffi.Struct {
  @ffi.Int32()
  external int theme_mode;

  @ffi.Int32()
  external int grid_columns;

  @ffi.Int32()
  external int album_grid_columns;

  @ffi.Int32()
  external int show_content_previews;

  @ffi.Int32()
  external int thumbnail_quality;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> language;

  @ffi.Int32()
  external int dynamic_color;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> last_scan_path;
}

final class wire_cst_search_filter extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> query;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> media_type;

  external ffi.Pointer<ffi.Int64> start_date;

  external ffi.Pointer<ffi.Int64> end_date;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> album_id;

  external ffi.Pointer<wire_cst_list_String> tag_ids;

  external ffi.Pointer<ffi.Int32> tag_count;
}

final class wire_cst_media_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> original_name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> storage_name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> thumbnail_path;

  @ffi.Int32()
  external int media_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> mime_type;

  @ffi.Int64()
  external int size;

  external ffi.Pointer<ffi.Int32> width;

  external ffi.Pointer<ffi.Int32> height;

  external ffi.Pointer<ffi.Int64> duration;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> sha256_hash;

  @ffi.Int64()
  external int created_at;

  @ffi.Int64()
  external int updated_at;
}

final class wire_cst_adjacent_media extends ffi.Struct {
  external ffi.Pointer<wire_cst_media_item> previous;

  external wire_cst_media_item current;

  external ffi.Pointer<wire_cst_media_item> next;
}

final class wire_cst_note extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> media_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> content;

  @ffi.Int64()
  external int created_at;

  @ffi.Int64()
  external int updated_at;
}

final class wire_cst_album extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cover_media_id;

  @ffi.Int32()
  external int sort_order;

  @ffi.Int64()
  external int created_at;
}

final class wire_cst_album_with_info extends ffi.Struct {
  external wire_cst_album album;

  @ffi.Int32()
  external int media_count;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cover_thumbnail_path;

  @ffi.Int32()
  external int has_children;
}

final class wire_cst_list_album_with_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_album_with_info> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_breadcrumb_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;
}

final class wire_cst_list_breadcrumb_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_breadcrumb_item> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_media_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_media_item> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_note extends ffi.Struct {
  external ffi.Pointer<wire_cst_note> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_tag extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> color;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id;

  @ffi.Int64()
  external int created_at;
}

final class wire_cst_list_tag extends ffi.Struct {
  external ffi.Pointer<wire_cst_tag> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_tag_breadcrumb extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;
}

final class wire_cst_list_tag_breadcrumb extends ffi.Struct {
  external ffi.Pointer<wire_cst_tag_breadcrumb> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_tag_with_info extends ffi.Struct {
  external wire_cst_tag tag;

  @ffi.Int32()
  external int media_count;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cover_thumbnail_path;

  @ffi.Int32()
  external int has_children;
}

final class wire_cst_list_tag_with_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_tag_with_info> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_export_progress extends ffi.Struct {
  @ffi.Int32()
  external int total_files;

  @ffi.Int32()
  external int processed_files;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> current_file;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;
}

final class wire_cst_import_progress extends ffi.Struct {
  @ffi.Int32()
  external int total_files;

  @ffi.Int32()
  external int processed_files;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> current_phase;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;
}

final class wire_cst_scan_result extends ffi.Struct {
  @ffi.Int32()
  external int imported_count;

  @ffi.Int32()
  external int duplicate_count;

  @ffi.Int32()
  external int failed_count;

  external ffi.Pointer<wire_cst_list_media_item> media_items;
}

final class wire_cst_storage_stats extends ffi.Struct {
  @ffi.Int32()
  external int total_media_count;

  @ffi.Int64()
  external int total_size;

  @ffi.Int64()
  external int thumbnail_cache_size;

  @ffi.Int64()
  external int database_size;
}
