// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/album.dart';
import 'api/import_export.dart';
import 'api/media.dart';
import 'api/note.dart';
import 'api/scanner.dart';
import 'api/search.dart';
import 'api/settings.dart';
import 'api/tag.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdjacentMedia dco_decode_adjacent_media(dynamic raw);

  @protected
  Album dco_decode_album(dynamic raw);

  @protected
  AlbumWithInfo dco_decode_album_with_info(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AdjacentMedia dco_decode_box_autoadd_adjacent_media(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MediaItem dco_decode_box_autoadd_media_item(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  SearchFilter dco_decode_box_autoadd_search_filter(dynamic raw);

  @protected
  BreadcrumbItem dco_decode_breadcrumb_item(dynamic raw);

  @protected
  ConflictStrategy dco_decode_conflict_strategy(dynamic raw);

  @protected
  ExportProgress dco_decode_export_progress(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportProgress dco_decode_import_progress(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlbumWithInfo> dco_decode_list_album_with_info(dynamic raw);

  @protected
  List<BreadcrumbItem> dco_decode_list_breadcrumb_item(dynamic raw);

  @protected
  List<MediaItem> dco_decode_list_media_item(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw);

  @protected
  List<TagBreadcrumb> dco_decode_list_tag_breadcrumb(dynamic raw);

  @protected
  List<TagWithInfo> dco_decode_list_tag_with_info(dynamic raw);

  @protected
  MediaItem dco_decode_media_item(dynamic raw);

  @protected
  MediaType dco_decode_media_type(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AdjacentMedia? dco_decode_opt_box_autoadd_adjacent_media(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MediaItem? dco_decode_opt_box_autoadd_media_item(dynamic raw);

  @protected
  Note? dco_decode_opt_box_autoadd_note(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  ScanResult dco_decode_scan_result(dynamic raw);

  @protected
  SearchFilter dco_decode_search_filter(dynamic raw);

  @protected
  StorageStats dco_decode_storage_stats(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  TagBreadcrumb dco_decode_tag_breadcrumb(dynamic raw);

  @protected
  TagWithInfo dco_decode_tag_with_info(dynamic raw);

  @protected
  ThemeMode dco_decode_theme_mode(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdjacentMedia sse_decode_adjacent_media(SseDeserializer deserializer);

  @protected
  Album sse_decode_album(SseDeserializer deserializer);

  @protected
  AlbumWithInfo sse_decode_album_with_info(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AdjacentMedia sse_decode_box_autoadd_adjacent_media(
      SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaItem sse_decode_box_autoadd_media_item(SseDeserializer deserializer);

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_box_autoadd_search_filter(
      SseDeserializer deserializer);

  @protected
  BreadcrumbItem sse_decode_breadcrumb_item(SseDeserializer deserializer);

  @protected
  ConflictStrategy sse_decode_conflict_strategy(SseDeserializer deserializer);

  @protected
  ExportProgress sse_decode_export_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportProgress sse_decode_import_progress(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlbumWithInfo> sse_decode_list_album_with_info(
      SseDeserializer deserializer);

  @protected
  List<BreadcrumbItem> sse_decode_list_breadcrumb_item(
      SseDeserializer deserializer);

  @protected
  List<MediaItem> sse_decode_list_media_item(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer);

  @protected
  List<TagBreadcrumb> sse_decode_list_tag_breadcrumb(
      SseDeserializer deserializer);

  @protected
  List<TagWithInfo> sse_decode_list_tag_with_info(SseDeserializer deserializer);

  @protected
  MediaItem sse_decode_media_item(SseDeserializer deserializer);

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer);

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AdjacentMedia? sse_decode_opt_box_autoadd_adjacent_media(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaItem? sse_decode_opt_box_autoadd_media_item(
      SseDeserializer deserializer);

  @protected
  Note? sse_decode_opt_box_autoadd_note(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  ScanResult sse_decode_scan_result(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_search_filter(SseDeserializer deserializer);

  @protected
  StorageStats sse_decode_storage_stats(SseDeserializer deserializer);

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  TagBreadcrumb sse_decode_tag_breadcrumb(SseDeserializer deserializer);

  @protected
  TagWithInfo sse_decode_tag_with_info(SseDeserializer deserializer);

  @protected
  ThemeMode sse_decode_theme_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_adjacent_media(AdjacentMedia raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_media_item(raw.previous),
      cst_encode_media_item(raw.current),
      cst_encode_opt_box_autoadd_media_item(raw.next)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_album(Album raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_opt_String(raw.parentId),
      cst_encode_opt_String(raw.coverMediaId),
      cst_encode_i_32(raw.sortOrder),
      cst_encode_i_64(raw.createdAt)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_album_with_info(AlbumWithInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_album(raw.album),
      cst_encode_i_32(raw.mediaCount),
      cst_encode_opt_String(raw.coverThumbnailPath),
      cst_encode_bool(raw.hasChildren)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_app_settings(AppSettings raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_theme_mode(raw.themeMode),
      cst_encode_i_32(raw.gridColumns),
      cst_encode_i_32(raw.albumGridColumns),
      cst_encode_bool(raw.showContentPreviews),
      cst_encode_i_32(raw.thumbnailQuality),
      cst_encode_String(raw.language)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_box_autoadd_adjacent_media(AdjacentMedia raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_adjacent_media(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_app_settings(AppSettings raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_app_settings(raw);
  }

  @protected
  int cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_media_item(MediaItem raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_media_item(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_note(Note raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_note(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_search_filter(SearchFilter raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_search_filter(raw);
  }

  @protected
  JSAny cst_encode_breadcrumb_item(BreadcrumbItem raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.id), cst_encode_String(raw.name)].jsify()!;
  }

  @protected
  JSAny cst_encode_export_progress(ExportProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.totalFiles),
      cst_encode_i_32(raw.processedFiles),
      cst_encode_opt_String(raw.currentFile),
      cst_encode_String(raw.status)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_import_progress(ImportProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.totalFiles),
      cst_encode_i_32(raw.processedFiles),
      cst_encode_String(raw.currentPhase),
      cst_encode_String(raw.status)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_album_with_info(List<AlbumWithInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_album_with_info).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_breadcrumb_item(List<BreadcrumbItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_breadcrumb_item).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_media_item(List<MediaItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_media_item).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_tag(List<Tag> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_tag).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_tag_breadcrumb(List<TagBreadcrumb> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_tag_breadcrumb).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_tag_with_info(List<TagWithInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_tag_with_info).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_media_item(MediaItem raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.originalName),
      cst_encode_String(raw.storageName),
      cst_encode_String(raw.filePath),
      cst_encode_String(raw.thumbnailPath),
      cst_encode_media_type(raw.mediaType),
      cst_encode_String(raw.mimeType),
      cst_encode_i_64(raw.size),
      cst_encode_opt_box_autoadd_i_32(raw.width),
      cst_encode_opt_box_autoadd_i_32(raw.height),
      cst_encode_opt_box_autoadd_i_64(raw.duration),
      cst_encode_String(raw.sha256Hash),
      cst_encode_i_64(raw.createdAt),
      cst_encode_i_64(raw.updatedAt)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_note(Note raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.mediaId),
      cst_encode_String(raw.content),
      cst_encode_i_64(raw.createdAt),
      cst_encode_i_64(raw.updatedAt)
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_adjacent_media(AdjacentMedia? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_adjacent_media(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_media_item(MediaItem? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_media_item(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_note(Note? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_note(raw);
  }

  @protected
  JSAny? cst_encode_opt_list_String(List<String>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_String(raw);
  }

  @protected
  JSAny cst_encode_scan_result(ScanResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.importedCount),
      cst_encode_i_32(raw.duplicateCount),
      cst_encode_i_32(raw.failedCount),
      cst_encode_list_media_item(raw.mediaItems)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_search_filter(SearchFilter raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.query),
      cst_encode_opt_String(raw.mediaType),
      cst_encode_opt_box_autoadd_i_64(raw.startDate),
      cst_encode_opt_box_autoadd_i_64(raw.endDate),
      cst_encode_opt_String(raw.albumId),
      cst_encode_opt_list_String(raw.tagIds),
      cst_encode_opt_box_autoadd_i_32(raw.tagCount)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_storage_stats(StorageStats raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.totalMediaCount),
      cst_encode_i_64(raw.totalSize),
      cst_encode_i_64(raw.thumbnailCacheSize),
      cst_encode_i_64(raw.databaseSize)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_tag(Tag raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_opt_String(raw.color),
      cst_encode_opt_String(raw.parentId),
      cst_encode_i_64(raw.createdAt)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_tag_breadcrumb(TagBreadcrumb raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.id), cst_encode_String(raw.name)].jsify()!;
  }

  @protected
  JSAny cst_encode_tag_with_info(TagWithInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_tag(raw.tag),
      cst_encode_i_32(raw.mediaCount),
      cst_encode_opt_String(raw.coverThumbnailPath),
      cst_encode_bool(raw.hasChildren)
    ].jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_conflict_strategy(ConflictStrategy raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_media_type(MediaType raw);

  @protected
  int cst_encode_theme_mode(ThemeMode raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_adjacent_media(AdjacentMedia self, SseSerializer serializer);

  @protected
  void sse_encode_album(Album self, SseSerializer serializer);

  @protected
  void sse_encode_album_with_info(AlbumWithInfo self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_adjacent_media(
      AdjacentMedia self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
      AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_item(
      MediaItem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_filter(
      SearchFilter self, SseSerializer serializer);

  @protected
  void sse_encode_breadcrumb_item(
      BreadcrumbItem self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_strategy(
      ConflictStrategy self, SseSerializer serializer);

  @protected
  void sse_encode_export_progress(
      ExportProgress self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_progress(
      ImportProgress self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_with_info(
      List<AlbumWithInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_breadcrumb_item(
      List<BreadcrumbItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_item(
      List<MediaItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_breadcrumb(
      List<TagBreadcrumb> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_with_info(
      List<TagWithInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_media_item(MediaItem self, SseSerializer serializer);

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer);

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_adjacent_media(
      AdjacentMedia? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_item(
      MediaItem? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_note(Note? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_scan_result(ScanResult self, SseSerializer serializer);

  @protected
  void sse_encode_search_filter(SearchFilter self, SseSerializer serializer);

  @protected
  void sse_encode_storage_stats(StorageStats self, SseSerializer serializer);

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_tag_breadcrumb(TagBreadcrumb self, SseSerializer serializer);

  @protected
  void sse_encode_tag_with_info(TagWithInfo self, SseSerializer serializer);

  @protected
  void sse_encode_theme_mode(ThemeMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__album__add_media_to_album(
          NativePortType port_, JSAny media_ids, String album_id) =>
      wasmModule.wire__crate__api__album__add_media_to_album(
          port_, media_ids, album_id);

  void wire__crate__api__tag__add_tag_to_media(
          NativePortType port_, String media_id, String tag_id) =>
      wasmModule.wire__crate__api__tag__add_tag_to_media(
          port_, media_id, tag_id);

  void wire__crate__api__scanner__calculate_file_hash(
          NativePortType port_, String file_path) =>
      wasmModule.wire__crate__api__scanner__calculate_file_hash(
          port_, file_path);

  void wire__crate__api__settings__clear_thumbnail_cache(
          NativePortType port_) =>
      wasmModule.wire__crate__api__settings__clear_thumbnail_cache(port_);

  void wire__crate__api__album__create_album(
          NativePortType port_, String name, String? parent_id) =>
      wasmModule.wire__crate__api__album__create_album(port_, name, parent_id);

  void wire__crate__api__tag__create_tag(NativePortType port_, String name,
          String? color, String? parent_id) =>
      wasmModule.wire__crate__api__tag__create_tag(
          port_, name, color, parent_id);

  void wire__crate__api__album__delete_album(NativePortType port_, String id) =>
      wasmModule.wire__crate__api__album__delete_album(port_, id);

  void wire__crate__api__settings__delete_all_data(NativePortType port_) =>
      wasmModule.wire__crate__api__settings__delete_all_data(port_);

  void wire__crate__api__media__delete_media(NativePortType port_, String id) =>
      wasmModule.wire__crate__api__media__delete_media(port_, id);

  void wire__crate__api__note__delete_note(NativePortType port_, String id) =>
      wasmModule.wire__crate__api__note__delete_note(port_, id);

  void wire__crate__api__tag__delete_tag(NativePortType port_, String id) =>
      wasmModule.wire__crate__api__tag__delete_tag(port_, id);

  void wire__crate__api__album__ensure_default_album(
          NativePortType port_, String name) =>
      wasmModule.wire__crate__api__album__ensure_default_album(port_, name);

  void wire__crate__api__tag__ensure_default_tag(
          NativePortType port_, String name, String? color) =>
      wasmModule.wire__crate__api__tag__ensure_default_tag(port_, name, color);

  void wire__crate__api__settings__export_data(
          NativePortType port_, String export_path) =>
      wasmModule.wire__crate__api__settings__export_data(port_, export_path);

  void wire__crate__api__import_export__export_package(
          NativePortType port_, String export_path, bool include_media) =>
      wasmModule.wire__crate__api__import_export__export_package(
          port_, export_path, include_media);

  void wire__crate__api__import_export__export_to_download(
          NativePortType port_, JSAny media_ids) =>
      wasmModule.wire__crate__api__import_export__export_to_download(
          port_, media_ids);

  void wire__crate__api__media__filter_media_by_type(
          NativePortType port_, int media_type) =>
      wasmModule.wire__crate__api__media__filter_media_by_type(
          port_, media_type);

  void wire__crate__api__scanner__generate_thumbnail(
          NativePortType port_, String file_path, int quality) =>
      wasmModule.wire__crate__api__scanner__generate_thumbnail(
          port_, file_path, quality);

  void wire__crate__api__media__get_adjacent_media(
          NativePortType port_, String id) =>
      wasmModule.wire__crate__api__media__get_adjacent_media(port_, id);

  void wire__crate__api__album__get_album_breadcrumb(
          NativePortType port_, String album_id) =>
      wasmModule.wire__crate__api__album__get_album_breadcrumb(port_, album_id);

  void wire__crate__api__media__get_all_media(NativePortType port_) =>
      wasmModule.wire__crate__api__media__get_all_media(port_);

  void wire__crate__api__tag__get_all_tags(NativePortType port_) =>
      wasmModule.wire__crate__api__tag__get_all_tags(port_);

  void wire__crate__api__album__get_child_albums(
          NativePortType port_, String parent_id) =>
      wasmModule.wire__crate__api__album__get_child_albums(port_, parent_id);

  void wire__crate__api__tag__get_child_tags(
          NativePortType port_, String parent_id) =>
      wasmModule.wire__crate__api__tag__get_child_tags(port_, parent_id);

  void wire__crate__api__media__get_media_by_id(
          NativePortType port_, String id) =>
      wasmModule.wire__crate__api__media__get_media_by_id(port_, id);

  void wire__crate__api__tag__get_media_by_tags_and(
          NativePortType port_, JSAny tag_ids) =>
      wasmModule.wire__crate__api__tag__get_media_by_tags_and(port_, tag_ids);

  void wire__crate__api__tag__get_media_by_tags_or(
          NativePortType port_, JSAny tag_ids) =>
      wasmModule.wire__crate__api__tag__get_media_by_tags_or(port_, tag_ids);

  void wire__crate__api__tag__get_media_tags(
          NativePortType port_, String media_id) =>
      wasmModule.wire__crate__api__tag__get_media_tags(port_, media_id);

  void wire__crate__api__search__get_media_with_any_album(
          NativePortType port_) =>
      wasmModule.wire__crate__api__search__get_media_with_any_album(port_);

  void wire__crate__api__search__get_media_with_any_tag(NativePortType port_) =>
      wasmModule.wire__crate__api__search__get_media_with_any_tag(port_);

  void wire__crate__api__search__get_media_without_any_album(
          NativePortType port_) =>
      wasmModule.wire__crate__api__search__get_media_without_any_album(port_);

  void wire__crate__api__search__get_media_without_any_tag(
          NativePortType port_) =>
      wasmModule.wire__crate__api__search__get_media_without_any_tag(port_);

  void wire__crate__api__note__get_note_by_media_id(
          NativePortType port_, String media_id) =>
      wasmModule.wire__crate__api__note__get_note_by_media_id(port_, media_id);

  void wire__crate__api__album__get_root_albums(NativePortType port_) =>
      wasmModule.wire__crate__api__album__get_root_albums(port_);

  void wire__crate__api__tag__get_root_tags(NativePortType port_) =>
      wasmModule.wire__crate__api__tag__get_root_tags(port_);

  void wire__crate__api__settings__get_settings(NativePortType port_) =>
      wasmModule.wire__crate__api__settings__get_settings(port_);

  void wire__crate__api__settings__get_storage_stats(NativePortType port_) =>
      wasmModule.wire__crate__api__settings__get_storage_stats(port_);

  void wire__crate__api__scanner__get_supported_extensions(
          NativePortType port_) =>
      wasmModule.wire__crate__api__scanner__get_supported_extensions(port_);

  void wire__crate__api__tag__get_tag_breadcrumb(
          NativePortType port_, String tag_id) =>
      wasmModule.wire__crate__api__tag__get_tag_breadcrumb(port_, tag_id);

  void wire__crate__api__settings__import_data(
          NativePortType port_, String import_path) =>
      wasmModule.wire__crate__api__settings__import_data(port_, import_path);

  void wire__crate__api__import_export__import_package(
          NativePortType port_, String package_path, int conflict_strategy) =>
      wasmModule.wire__crate__api__import_export__import_package(
          port_, package_path, conflict_strategy);

  void wire__crate__api__scanner__is_hash_exists(
          NativePortType port_, String hash) =>
      wasmModule.wire__crate__api__scanner__is_hash_exists(port_, hash);

  void wire__crate__api__album__remove_media_from_album(
          NativePortType port_, JSAny media_ids, String album_id) =>
      wasmModule.wire__crate__api__album__remove_media_from_album(
          port_, media_ids, album_id);

  void wire__crate__api__tag__remove_tag_from_media(
          NativePortType port_, String media_id, String tag_id) =>
      wasmModule.wire__crate__api__tag__remove_tag_from_media(
          port_, media_id, tag_id);

  void wire__crate__api__album__rename_album(
          NativePortType port_, String id, String new_name) =>
      wasmModule.wire__crate__api__album__rename_album(port_, id, new_name);

  void wire__crate__api__tag__rename_tag(
          NativePortType port_, String id, String new_name) =>
      wasmModule.wire__crate__api__tag__rename_tag(port_, id, new_name);

  void wire__crate__api__note__save_note(
          NativePortType port_, String media_id, String content) =>
      wasmModule.wire__crate__api__note__save_note(port_, media_id, content);

  void wire__crate__api__settings__save_settings(
          NativePortType port_, JSAny settings) =>
      wasmModule.wire__crate__api__settings__save_settings(port_, settings);

  void wire__crate__api__scanner__scan_directory(
          NativePortType port_, String path) =>
      wasmModule.wire__crate__api__scanner__scan_directory(port_, path);

  void wire__crate__api__search__search_filter_default(NativePortType port_) =>
      wasmModule.wire__crate__api__search__search_filter_default(port_);

  void wire__crate__api__media__search_media(
          NativePortType port_, String query) =>
      wasmModule.wire__crate__api__media__search_media(port_, query);

  void wire__crate__api__search__search_media_advanced(
          NativePortType port_, JSAny filter) =>
      wasmModule.wire__crate__api__search__search_media_advanced(port_, filter);

  void wire__crate__api__album__set_album_cover(
          NativePortType port_, String album_id, String media_id) =>
      wasmModule.wire__crate__api__album__set_album_cover(
          port_, album_id, media_id);

  void wire__crate__api__media__update_media(
          NativePortType port_, JSAny media) =>
      wasmModule.wire__crate__api__media__update_media(port_, media);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__album__add_media_to_album(
      NativePortType port_, JSAny media_ids, String album_id);

  external void wire__crate__api__tag__add_tag_to_media(
      NativePortType port_, String media_id, String tag_id);

  external void wire__crate__api__scanner__calculate_file_hash(
      NativePortType port_, String file_path);

  external void wire__crate__api__settings__clear_thumbnail_cache(
      NativePortType port_);

  external void wire__crate__api__album__create_album(
      NativePortType port_, String name, String? parent_id);

  external void wire__crate__api__tag__create_tag(
      NativePortType port_, String name, String? color, String? parent_id);

  external void wire__crate__api__album__delete_album(
      NativePortType port_, String id);

  external void wire__crate__api__settings__delete_all_data(
      NativePortType port_);

  external void wire__crate__api__media__delete_media(
      NativePortType port_, String id);

  external void wire__crate__api__note__delete_note(
      NativePortType port_, String id);

  external void wire__crate__api__tag__delete_tag(
      NativePortType port_, String id);

  external void wire__crate__api__album__ensure_default_album(
      NativePortType port_, String name);

  external void wire__crate__api__tag__ensure_default_tag(
      NativePortType port_, String name, String? color);

  external void wire__crate__api__settings__export_data(
      NativePortType port_, String export_path);

  external void wire__crate__api__import_export__export_package(
      NativePortType port_, String export_path, bool include_media);

  external void wire__crate__api__import_export__export_to_download(
      NativePortType port_, JSAny media_ids);

  external void wire__crate__api__media__filter_media_by_type(
      NativePortType port_, int media_type);

  external void wire__crate__api__scanner__generate_thumbnail(
      NativePortType port_, String file_path, int quality);

  external void wire__crate__api__media__get_adjacent_media(
      NativePortType port_, String id);

  external void wire__crate__api__album__get_album_breadcrumb(
      NativePortType port_, String album_id);

  external void wire__crate__api__media__get_all_media(NativePortType port_);

  external void wire__crate__api__tag__get_all_tags(NativePortType port_);

  external void wire__crate__api__album__get_child_albums(
      NativePortType port_, String parent_id);

  external void wire__crate__api__tag__get_child_tags(
      NativePortType port_, String parent_id);

  external void wire__crate__api__media__get_media_by_id(
      NativePortType port_, String id);

  external void wire__crate__api__tag__get_media_by_tags_and(
      NativePortType port_, JSAny tag_ids);

  external void wire__crate__api__tag__get_media_by_tags_or(
      NativePortType port_, JSAny tag_ids);

  external void wire__crate__api__tag__get_media_tags(
      NativePortType port_, String media_id);

  external void wire__crate__api__search__get_media_with_any_album(
      NativePortType port_);

  external void wire__crate__api__search__get_media_with_any_tag(
      NativePortType port_);

  external void wire__crate__api__search__get_media_without_any_album(
      NativePortType port_);

  external void wire__crate__api__search__get_media_without_any_tag(
      NativePortType port_);

  external void wire__crate__api__note__get_note_by_media_id(
      NativePortType port_, String media_id);

  external void wire__crate__api__album__get_root_albums(NativePortType port_);

  external void wire__crate__api__tag__get_root_tags(NativePortType port_);

  external void wire__crate__api__settings__get_settings(NativePortType port_);

  external void wire__crate__api__settings__get_storage_stats(
      NativePortType port_);

  external void wire__crate__api__scanner__get_supported_extensions(
      NativePortType port_);

  external void wire__crate__api__tag__get_tag_breadcrumb(
      NativePortType port_, String tag_id);

  external void wire__crate__api__settings__import_data(
      NativePortType port_, String import_path);

  external void wire__crate__api__import_export__import_package(
      NativePortType port_, String package_path, int conflict_strategy);

  external void wire__crate__api__scanner__is_hash_exists(
      NativePortType port_, String hash);

  external void wire__crate__api__album__remove_media_from_album(
      NativePortType port_, JSAny media_ids, String album_id);

  external void wire__crate__api__tag__remove_tag_from_media(
      NativePortType port_, String media_id, String tag_id);

  external void wire__crate__api__album__rename_album(
      NativePortType port_, String id, String new_name);

  external void wire__crate__api__tag__rename_tag(
      NativePortType port_, String id, String new_name);

  external void wire__crate__api__note__save_note(
      NativePortType port_, String media_id, String content);

  external void wire__crate__api__settings__save_settings(
      NativePortType port_, JSAny settings);

  external void wire__crate__api__scanner__scan_directory(
      NativePortType port_, String path);

  external void wire__crate__api__search__search_filter_default(
      NativePortType port_);

  external void wire__crate__api__media__search_media(
      NativePortType port_, String query);

  external void wire__crate__api__search__search_media_advanced(
      NativePortType port_, JSAny filter);

  external void wire__crate__api__album__set_album_cover(
      NativePortType port_, String album_id, String media_id);

  external void wire__crate__api__media__update_media(
      NativePortType port_, JSAny media);
}
