// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Skill-01 §2.4 - FilterMode 枚举
/// 用于首页"所有媒体"Tab 的内容过滤器
enum FilterMode {
  /// 显示全部媒体
  all,

  /// 仅显示已打标签的媒体
  withTags,

  /// 仅显示未打标签的媒体
  withoutTags,

  /// 仅显示已加入相册的媒体
  withAlbums,

  /// 仅显示未加入相册的媒体
  withoutAlbums,
  ;

  Future<void> asStr() => RustLib.instance.api.crateApiEnumsFilterModeAsStr(
        that: this,
      );

  Future<void> displayName() =>
      RustLib.instance.api.crateApiEnumsFilterModeDisplayName(
        that: this,
      );
}

/// Skill-01 §2.3 - Language 枚举（设置用）
enum LanguageSetting {
  system,
  zh,
  en,
  ;

  Future<void> asStr() =>
      RustLib.instance.api.crateApiEnumsLanguageSettingAsStr(
        that: this,
      );

  static Future<LanguageSetting> fromStr({required String s}) =>
      RustLib.instance.api.crateApiEnumsLanguageSettingFromStr(s: s);
}

/// Skill-01 §2.2 - ThemeMode 枚举（设置用）
enum ThemeModeSetting {
  system,
  light,
  dark,
  ;

  Future<void> asStr() =>
      RustLib.instance.api.crateApiEnumsThemeModeSettingAsStr(
        that: this,
      );

  static Future<ThemeModeSetting> fromStr({required String s}) =>
      RustLib.instance.api.crateApiEnumsThemeModeSettingFromStr(s: s);
}
