// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// 导入包（ZIP 格式的数据库备份 + 媒体文件）
Future<ImportProgress> importPackage(
        {required String packagePath,
        required ConflictStrategy conflictStrategy}) =>
    RustLib.instance.api.crateApiImportExportImportPackage(
        packagePath: packagePath, conflictStrategy: conflictStrategy);

/// 导出数据包（导出数据库 + 媒体文件为 ZIP）
Future<ExportProgress> exportPackage(
        {required String exportPath, required bool includeMedia}) =>
    RustLib.instance.api.crateApiImportExportExportPackage(
        exportPath: exportPath, includeMedia: includeMedia);

/// 导出指定媒体到下载目录
Future<String> exportToDownload({required List<String> mediaIds}) =>
    RustLib.instance.api
        .crateApiImportExportExportToDownload(mediaIds: mediaIds);

/// 冲突策略
enum ConflictStrategy {
  skip,
  replace,
  rename,
  ;
}

/// 导出进度
class ExportProgress {
  final int totalFiles;
  final int processedFiles;
  final String? currentFile;
  final String status;

  const ExportProgress({
    required this.totalFiles,
    required this.processedFiles,
    this.currentFile,
    required this.status,
  });

  @override
  int get hashCode =>
      totalFiles.hashCode ^
      processedFiles.hashCode ^
      currentFile.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportProgress &&
          runtimeType == other.runtimeType &&
          totalFiles == other.totalFiles &&
          processedFiles == other.processedFiles &&
          currentFile == other.currentFile &&
          status == other.status;
}

/// 导入进度
class ImportProgress {
  final int totalFiles;
  final int processedFiles;
  final String currentPhase;
  final String status;

  const ImportProgress({
    required this.totalFiles,
    required this.processedFiles,
    required this.currentPhase,
    required this.status,
  });

  @override
  int get hashCode =>
      totalFiles.hashCode ^
      processedFiles.hashCode ^
      currentPhase.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportProgress &&
          runtimeType == other.runtimeType &&
          totalFiles == other.totalFiles &&
          processedFiles == other.processedFiles &&
          currentPhase == other.currentPhase &&
          status == other.status;
}
