// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// 获取所有媒体列表
Future<List<MediaItem>> getAllMedia() =>
    RustLib.instance.api.crateApiMediaGetAllMedia();

/// 按ID获取媒体
Future<MediaItem?> getMediaById({required String id}) =>
    RustLib.instance.api.crateApiMediaGetMediaById(id: id);

/// 删除媒体
Future<void> deleteMedia({required String id}) =>
    RustLib.instance.api.crateApiMediaDeleteMedia(id: id);

/// 获取相邻媒体
Future<AdjacentMedia?> getAdjacentMedia({required String id}) =>
    RustLib.instance.api.crateApiMediaGetAdjacentMedia(id: id);

/// 搜索媒体
Future<List<MediaItem>> searchMedia({required String query}) =>
    RustLib.instance.api.crateApiMediaSearchMedia(query: query);

/// 按类型过滤媒体
Future<List<MediaItem>> filterMediaByType({required MediaType mediaType}) =>
    RustLib.instance.api.crateApiMediaFilterMediaByType(mediaType: mediaType);

/// 更新媒体信息
Future<void> updateMedia({required MediaItem media}) =>
    RustLib.instance.api.crateApiMediaUpdateMedia(media: media);

/// 相邻媒体（用于查看器导航）
class AdjacentMedia {
  final MediaItem? previous;
  final MediaItem current;
  final MediaItem? next;

  const AdjacentMedia({
    this.previous,
    required this.current,
    this.next,
  });

  @override
  int get hashCode => previous.hashCode ^ current.hashCode ^ next.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdjacentMedia &&
          runtimeType == other.runtimeType &&
          previous == other.previous &&
          current == other.current &&
          next == other.next;
}

/// 媒体项实体（对应参考项目的 MediaItemEntity）
class MediaItem {
  final String id;
  final String originalName;
  final String storageName;
  final String filePath;
  final String thumbnailPath;
  final MediaType mediaType;
  final String mimeType;
  final PlatformInt64 size;
  final int? width;
  final int? height;
  final PlatformInt64? duration;
  final String sha256Hash;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const MediaItem({
    required this.id,
    required this.originalName,
    required this.storageName,
    required this.filePath,
    required this.thumbnailPath,
    required this.mediaType,
    required this.mimeType,
    required this.size,
    this.width,
    this.height,
    this.duration,
    required this.sha256Hash,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      originalName.hashCode ^
      storageName.hashCode ^
      filePath.hashCode ^
      thumbnailPath.hashCode ^
      mediaType.hashCode ^
      mimeType.hashCode ^
      size.hashCode ^
      width.hashCode ^
      height.hashCode ^
      duration.hashCode ^
      sha256Hash.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          originalName == other.originalName &&
          storageName == other.storageName &&
          filePath == other.filePath &&
          thumbnailPath == other.thumbnailPath &&
          mediaType == other.mediaType &&
          mimeType == other.mimeType &&
          size == other.size &&
          width == other.width &&
          height == other.height &&
          duration == other.duration &&
          sha256Hash == other.sha256Hash &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 媒体类型枚举
enum MediaType {
  image,
  video,
  audio,
  unknown,
  ;
}
