// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'media.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_file_hash_sync`, `determine_media_type`, `generate_thumbnail_path`, `generate_thumbnail_sync`, `get_image_dimensions`, `get_supported_extensions_set`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ScanProgress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 扫描目录并导入媒体
Future<ScanResult> scanDirectory({required String path}) =>
    RustLib.instance.api.crateApiScannerScanDirectory(path: path);

/// 生成缩略图
Future<String> generateThumbnail(
        {required String filePath, required int quality}) =>
    RustLib.instance.api
        .crateApiScannerGenerateThumbnail(filePath: filePath, quality: quality);

/// 计算文件 SHA256 哈希
Future<String> calculateFileHash({required String filePath}) =>
    RustLib.instance.api.crateApiScannerCalculateFileHash(filePath: filePath);

/// 检查文件是否已存在（通过哈希）
Future<bool> isHashExists({required String hash}) =>
    RustLib.instance.api.crateApiScannerIsHashExists(hash: hash);

/// 支持的媒体扩展名列表
Future<List<String>> getSupportedExtensions() =>
    RustLib.instance.api.crateApiScannerGetSupportedExtensions();

/// 导入单个文件
Future<MediaItem> importSingleFile({required String filePath}) =>
    RustLib.instance.api.crateApiScannerImportSingleFile(filePath: filePath);

/// 扫描结果
class ScanResult {
  final int importedCount;
  final int duplicateCount;
  final int failedCount;
  final List<MediaItem> mediaItems;

  const ScanResult({
    required this.importedCount,
    required this.duplicateCount,
    required this.failedCount,
    required this.mediaItems,
  });

  @override
  int get hashCode =>
      importedCount.hashCode ^
      duplicateCount.hashCode ^
      failedCount.hashCode ^
      mediaItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          importedCount == other.importedCount &&
          duplicateCount == other.duplicateCount &&
          failedCount == other.failedCount &&
          mediaItems == other.mediaItems;
}
