// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'media.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 综合搜索
Future<List<MediaItem>> searchMediaAdvanced({required SearchFilter filter}) =>
    RustLib.instance.api.crateApiSearchSearchMediaAdvanced(filter: filter);

/// 获取有标签的媒体
Future<List<MediaItem>> getMediaWithAnyTag() =>
    RustLib.instance.api.crateApiSearchGetMediaWithAnyTag();

/// 获取无标签的媒体
Future<List<MediaItem>> getMediaWithoutAnyTag() =>
    RustLib.instance.api.crateApiSearchGetMediaWithoutAnyTag();

/// 获取有相册的媒体
Future<List<MediaItem>> getMediaWithAnyAlbum() =>
    RustLib.instance.api.crateApiSearchGetMediaWithAnyAlbum();

/// 获取无相册的媒体
Future<List<MediaItem>> getMediaWithoutAnyAlbum() =>
    RustLib.instance.api.crateApiSearchGetMediaWithoutAnyAlbum();

/// 搜索筛选条件
class SearchFilter {
  final String? query;
  final String? mediaType;
  final PlatformInt64? startDate;
  final PlatformInt64? endDate;
  final String? albumId;
  final List<String>? tagIds;
  final int? tagCount;

  const SearchFilter({
    this.query,
    this.mediaType,
    this.startDate,
    this.endDate,
    this.albumId,
    this.tagIds,
    this.tagCount,
  });

  static Future<SearchFilter> default_() =>
      RustLib.instance.api.crateApiSearchSearchFilterDefault();

  @override
  int get hashCode =>
      query.hashCode ^
      mediaType.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      albumId.hashCode ^
      tagIds.hashCode ^
      tagCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchFilter &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          mediaType == other.mediaType &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          albumId == other.albumId &&
          tagIds == other.tagIds &&
          tagCount == other.tagCount;
}
