// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// 获取设置
Future<AppSettings> getSettings() =>
    RustLib.instance.api.crateApiSettingsGetSettings();

/// 保存设置
Future<void> saveSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(settings: settings);

/// 获取存储统计
Future<StorageStats> getStorageStats() =>
    RustLib.instance.api.crateApiSettingsGetStorageStats();

/// 清理缩略图缓存
Future<void> clearThumbnailCache() =>
    RustLib.instance.api.crateApiSettingsClearThumbnailCache();

/// 导出数据
Future<void> exportData({required String exportPath}) =>
    RustLib.instance.api.crateApiSettingsExportData(exportPath: exportPath);

/// 导入数据
Future<void> importData({required String importPath}) =>
    RustLib.instance.api.crateApiSettingsImportData(importPath: importPath);

/// 删除所有数据
Future<void> deleteAllData() =>
    RustLib.instance.api.crateApiSettingsDeleteAllData();

/// 应用设置
class AppSettings {
  final ThemeMode themeMode;
  final int gridColumns;
  final int albumGridColumns;
  final bool showContentPreviews;
  final int thumbnailQuality;
  final String language;

  const AppSettings({
    required this.themeMode,
    required this.gridColumns,
    required this.albumGridColumns,
    required this.showContentPreviews,
    required this.thumbnailQuality,
    required this.language,
  });

  @override
  int get hashCode =>
      themeMode.hashCode ^
      gridColumns.hashCode ^
      albumGridColumns.hashCode ^
      showContentPreviews.hashCode ^
      thumbnailQuality.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          gridColumns == other.gridColumns &&
          albumGridColumns == other.albumGridColumns &&
          showContentPreviews == other.showContentPreviews &&
          thumbnailQuality == other.thumbnailQuality &&
          language == other.language;
}

/// 存储统计
class StorageStats {
  final int totalMediaCount;
  final PlatformInt64 totalSize;
  final PlatformInt64 thumbnailCacheSize;
  final PlatformInt64 databaseSize;

  const StorageStats({
    required this.totalMediaCount,
    required this.totalSize,
    required this.thumbnailCacheSize,
    required this.databaseSize,
  });

  @override
  int get hashCode =>
      totalMediaCount.hashCode ^
      totalSize.hashCode ^
      thumbnailCacheSize.hashCode ^
      databaseSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageStats &&
          runtimeType == other.runtimeType &&
          totalMediaCount == other.totalMediaCount &&
          totalSize == other.totalSize &&
          thumbnailCacheSize == other.thumbnailCacheSize &&
          databaseSize == other.databaseSize;
}

/// 主题模式
enum ThemeMode {
  system,
  light,
  dark,
  ;
}
