// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'media.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_tags_by_parent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// 获取所有标签
Future<List<Tag>> getAllTags() => RustLib.instance.api.crateApiTagGetAllTags();

/// 获取根标签
Future<List<TagWithInfo>> getRootTags() =>
    RustLib.instance.api.crateApiTagGetRootTags();

/// 获取子标签
Future<List<TagWithInfo>> getChildTags({required String parentId}) =>
    RustLib.instance.api.crateApiTagGetChildTags(parentId: parentId);

/// 创建标签
Future<String> createTag(
        {required String name, String? color, String? parentId}) =>
    RustLib.instance.api
        .crateApiTagCreateTag(name: name, color: color, parentId: parentId);

/// 删除标签（级联删除子标签和媒体关联）
Future<void> deleteTag({required String id}) =>
    RustLib.instance.api.crateApiTagDeleteTag(id: id);

/// 重命名标签
Future<void> renameTag({required String id, required String newName}) =>
    RustLib.instance.api.crateApiTagRenameTag(id: id, newName: newName);

/// 获取标签面包屑路径
Future<List<TagBreadcrumb>> getTagBreadcrumb({required String tagId}) =>
    RustLib.instance.api.crateApiTagGetTagBreadcrumb(tagId: tagId);

/// 添加标签到媒体
Future<void> addTagToMedia({required String mediaId, required String tagId}) =>
    RustLib.instance.api
        .crateApiTagAddTagToMedia(mediaId: mediaId, tagId: tagId);

/// 从媒体移除标签
Future<void> removeTagFromMedia(
        {required String mediaId, required String tagId}) =>
    RustLib.instance.api
        .crateApiTagRemoveTagFromMedia(mediaId: mediaId, tagId: tagId);

/// 获取媒体的标签
Future<List<Tag>> getMediaTags({required String mediaId}) =>
    RustLib.instance.api.crateApiTagGetMediaTags(mediaId: mediaId);

/// 按标签筛选媒体（AND 模式 - 媒体必须包含所有指定标签）
Future<List<MediaItem>> getMediaByTagsAnd({required List<String> tagIds}) =>
    RustLib.instance.api.crateApiTagGetMediaByTagsAnd(tagIds: tagIds);

/// 按标签筛选媒体（OR 模式 - 媒体包含任意指定标签）
Future<List<MediaItem>> getMediaByTagsOr({required List<String> tagIds}) =>
    RustLib.instance.api.crateApiTagGetMediaByTagsOr(tagIds: tagIds);

/// 获取单个标签关联的媒体
Future<List<MediaItem>> getMediaByTag({required String tagId}) =>
    RustLib.instance.api.crateApiTagGetMediaByTag(tagId: tagId);

/// 确保默认标签存在（如果不存在则创建）
Future<String> ensureDefaultTag({required String name, String? color}) =>
    RustLib.instance.api.crateApiTagEnsureDefaultTag(name: name, color: color);

/// 标签实体
class Tag {
  final String id;
  final String name;
  final String? color;
  final String? parentId;
  final PlatformInt64 createdAt;

  const Tag({
    required this.id,
    required this.name,
    this.color,
    this.parentId,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      parentId.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          parentId == other.parentId &&
          createdAt == other.createdAt;
}

/// 标签面包屑项
class TagBreadcrumb {
  final String id;
  final String name;

  const TagBreadcrumb({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagBreadcrumb &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

/// 标签信息（包含媒体数量和子标签标志）
class TagWithInfo {
  final Tag tag;
  final int mediaCount;
  final String? coverThumbnailPath;
  final int hasChildren;

  const TagWithInfo({
    required this.tag,
    required this.mediaCount,
    this.coverThumbnailPath,
    required this.hasChildren,
  });

  @override
  int get hashCode =>
      tag.hashCode ^
      mediaCount.hashCode ^
      coverThumbnailPath.hashCode ^
      hasChildren.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagWithInfo &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          mediaCount == other.mediaCount &&
          coverThumbnailPath == other.coverThumbnailPath &&
          hasChildren == other.hasChildren;
}
